package notification

import (
	"context"
	"os"
	"path/filepath"
	"runtime"
	"testing"
	"time"

	"admin/server/internal/config"
	"admin/server/internal/database/testschema"
	"admin/server/internal/module/realtime"
	"github.com/joho/godotenv"
	"gorm.io/gorm"
)

func TestCreateForUsersCommitsNotificationRecipientsAndRealtimeAtomically(t *testing.T) {
	db, ctx := openNotificationRepositoryDB(t)
	service := NewService(NewRepository(db, realtime.NewRepository(db)))
	input := validCreateForUsersInput(1, "source-one", []int64{3, 1, 2, 2})
	created, err := service.CreateForUsers(ctx, input)
	if err != nil {
		t.Fatal(err)
	}
	assertNotificationCounts(t, db, ctx, 1, 3, 3, 3)

	retry, err := service.CreateForUsers(ctx, input)
	if err != nil {
		t.Fatal(err)
	}
	if retry.ID != created.ID {
		t.Fatalf("retry id=%d created=%d", retry.ID, created.ID)
	}
	assertNotificationCounts(t, db, ctx, 1, 3, 3, 3)

	otherPlatform, err := service.CreateForUsers(ctx, validCreateForUsersInput(2, "source-one", []int64{1}))
	if err != nil || otherPlatform.ID == created.ID {
		t.Fatalf("other=%+v err=%v", otherPlatform, err)
	}
	assertNotificationCounts(t, db, ctx, 2, 4, 4, 4)
}

func TestCreateForUsersRollsBackWhenRealtimeAppendFails(t *testing.T) {
	db, ctx := openNotificationRepositoryDB(t)
	if err := db.WithContext(ctx).Exec(`CREATE FUNCTION reject_realtime_event() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced realtime failure'; END $$; CREATE TRIGGER reject_realtime BEFORE INSERT ON realtime_event FOR EACH ROW EXECUTE FUNCTION reject_realtime_event()`).Error; err != nil {
		t.Fatal(err)
	}
	service := NewService(NewRepository(db, realtime.NewRepository(db)))
	if _, err := service.CreateForUsers(ctx, validCreateForUsersInput(1, "rollback", []int64{1, 2})); err == nil {
		t.Fatal("CreateForUsers() error=nil")
	}
	assertNotificationCounts(t, db, ctx, 0, 0, 0, 0)
}

func TestCreateForUsersRejectsMissingPlatformAndUser(t *testing.T) {
	db, ctx := openNotificationRepositoryDB(t)
	service := NewService(NewRepository(db, realtime.NewRepository(db)))
	for _, input := range []CreateForUsersInput{
		validCreateForUsersInput(999, "missing-platform", []int64{1}),
		validCreateForUsersInput(1, "missing-user", []int64{999}),
	} {
		if _, err := service.CreateForUsers(ctx, input); err == nil {
			t.Fatalf("CreateForUsers(%+v) error=nil", input)
		}
	}
	assertNotificationCounts(t, db, ctx, 0, 0, 0, 0)
}

func validCreateForUsersInput(platformID int64, sourceKey string, users []int64) CreateForUsersInput {
	return CreateForUsersInput{PlatformID: platformID, SourceType: "system.test", SourceKey: sourceKey, UserIDs: users, Title: "Notice", ContentHTML: "<p>Hello <strong>world</strong></p>", Variant: VariantInfo, Priority: PriorityNormal, LinkType: LinkInternal, Link: "/message/notification", PublishedAt: time.Now().UTC()}
}

func assertNotificationCounts(t *testing.T, db *gorm.DB, ctx context.Context, notifications, recipients, events, outbox int64) {
	t.Helper()
	for table, want := range map[string]int64{"message_notification": notifications, "message_notification_recipient": recipients, "realtime_event": events, "realtime_event_outbox": outbox} {
		var got int64
		if err := db.WithContext(ctx).Raw("SELECT count(*) FROM " + table).Scan(&got).Error; err != nil {
			t.Fatal(err)
		}
		if got != want {
			t.Fatalf("%s count=%d want=%d", table, got, want)
		}
	}
}

func openNotificationRepositoryDB(t *testing.T) (*gorm.DB, context.Context) {
	t.Helper()
	db, ctx := testschema.Open(t, notificationRepositoryDSN(t), "test_notification_repository")
	statements := []string{
		`CREATE EXTENSION IF NOT EXISTS pgcrypto`,
		`CREATE TABLE permission_auth_platform(id BIGINT PRIMARY KEY)`,
		`CREATE TABLE user_account(id BIGINT PRIMARY KEY)`,
		`INSERT INTO permission_auth_platform(id) VALUES(1),(2)`,
		`INSERT INTO user_account(id) VALUES(1),(2),(3)`,
		`CREATE TABLE message_notification_task(id BIGINT PRIMARY KEY)`,
		`CREATE TABLE message_notification(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,platform_id BIGINT NOT NULL REFERENCES permission_auth_platform(id),source_task_id BIGINT NULL REFERENCES message_notification_task(id),source_type VARCHAR(64) NOT NULL,source_key VARCHAR(128) NOT NULL,audience_type VARCHAR(16) NOT NULL,audience_max_user_id BIGINT NOT NULL,title VARCHAR(128) NOT NULL,content_html TEXT NOT NULL,summary VARCHAR(256) NOT NULL,variant VARCHAR(16) NOT NULL,priority VARCHAR(16) NOT NULL,link_type VARCHAR(16) NOT NULL,link VARCHAR(2048) NOT NULL,published_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL)`,
		`CREATE UNIQUE INDEX ux_message_notification_source ON message_notification(platform_id,source_type,source_key)`,
		`CREATE TABLE message_notification_recipient(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,notification_id BIGINT NOT NULL REFERENCES message_notification(id) ON DELETE CASCADE,platform_id BIGINT NOT NULL REFERENCES permission_auth_platform(id),user_id BIGINT NOT NULL REFERENCES user_account(id),read_at TIMESTAMPTZ NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,deleted_at TIMESTAMPTZ NULL)`,
		`CREATE UNIQUE INDEX ux_message_notification_recipient_active ON message_notification_recipient(notification_id,user_id) WHERE deleted_at IS NULL`,
		`CREATE TABLE message_notification_broadcast_state(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,notification_id BIGINT NOT NULL REFERENCES message_notification(id) ON DELETE CASCADE,platform_id BIGINT NOT NULL REFERENCES permission_auth_platform(id),user_id BIGINT NOT NULL REFERENCES user_account(id),read_at TIMESTAMPTZ NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,deleted_at TIMESTAMPTZ NULL)`,
		`CREATE UNIQUE INDEX ux_message_notification_broadcast_state_active ON message_notification_broadcast_state(notification_id,user_id) WHERE deleted_at IS NULL`,
		`CREATE TABLE message_notification_mailbox_state(platform_id BIGINT NOT NULL REFERENCES permission_auth_platform(id),user_id BIGINT NOT NULL REFERENCES user_account(id),read_through_notification_id BIGINT NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,PRIMARY KEY(platform_id,user_id))`,
		`CREATE TABLE realtime_event(sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,event_id UUID NOT NULL UNIQUE,dedup_key VARCHAR(256) NOT NULL UNIQUE,platform_id BIGINT NOT NULL REFERENCES permission_auth_platform(id),event_type VARCHAR(64) NOT NULL,target_type VARCHAR(16) NOT NULL,target_user_id BIGINT NULL REFERENCES user_account(id),audience_max_user_id BIGINT NULL,payload JSONB NOT NULL,occurred_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL)`,
		`CREATE TABLE realtime_event_outbox(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,event_sequence BIGINT NOT NULL UNIQUE REFERENCES realtime_event(sequence) ON DELETE CASCADE,attempts INTEGER NOT NULL,available_at TIMESTAMPTZ NOT NULL,locked_until TIMESTAMPTZ NULL,lock_token VARCHAR(64) NULL,published_at TIMESTAMPTZ NULL,last_error VARCHAR(512) NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL)`,
	}
	for _, statement := range statements {
		if err := db.WithContext(ctx).Exec(statement).Error; err != nil {
			t.Fatal(err)
		}
	}
	return db, ctx
}

func notificationRepositoryDSN(t *testing.T) string {
	t.Helper()
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	repoRoot := filepath.Clean(filepath.Join(filepath.Dir(filename), "..", "..", "..", "..", ".."))
	if err := godotenv.Load(filepath.Join(repoRoot, "server", ".env")); err != nil && !os.IsNotExist(err) {
		t.Fatal(err)
	}
	settings, err := config.LoadWorker(os.LookupEnv)
	if err != nil {
		t.Fatal(err)
	}
	return settings.PostgresDSN
}
