package cachegeneration

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"testing"
	"time"

	"admin/server/internal/config"
	"admin/server/internal/database/testschema"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/joho/godotenv"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

func TestAdvanceTxCreatesDurableOutboxInTheSameTransaction(t *testing.T) {
	db, ctx := openGenerationDatabase(t)
	repository := NewRepository(db)
	scope, err := NewScope("system.setting", "global")
	if err != nil {
		t.Fatal(err)
	}
	now := time.Now().UTC()

	var event Event
	if err := db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		created, err := repository.AdvanceTx(ctx, tx, scope, 1, now)
		if err != nil {
			return err
		}
		event = created
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	if event.Generation != 2 || event.ID < 1 {
		t.Fatalf("event=%+v", event)
	}
	current, err := repository.Current(ctx, scope)
	if err != nil || current != 2 {
		t.Fatalf("generation=%d err=%v", current, err)
	}
	claimed, err := repository.ClaimPending(ctx, 10, "claim-token", time.Now().UTC(), time.Minute)
	if err != nil || len(claimed) != 1 || claimed[0].ID != event.ID {
		t.Fatalf("claimed=%+v err=%v", claimed, err)
	}
}

// loadIntegrationSettings resolves the repository root instead of a hard-coded
// relative path, mirroring the existing PostgreSQL integration test pattern.
func loadIntegrationSettings(t *testing.T) config.Worker {
	t.Helper()
	if testing.Short() {
		t.Skip("integration test")
	}
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	repoRoot := filepath.Clean(filepath.Join(filepath.Dir(filename), "..", "..", "..", ".."))
	if err := godotenv.Load(filepath.Join(repoRoot, "server", ".env")); err != nil && !os.IsNotExist(err) {
		t.Fatal(err)
	}
	settings, err := config.LoadWorker(os.LookupEnv)
	if err != nil {
		t.Fatal(err)
	}
	return settings
}

func openGenerationDatabase(t *testing.T) (*gorm.DB, context.Context) {
	t.Helper()
	settings := loadIntegrationSettings(t)
	db, ctx := testschema.Open(t, settings.PostgresDSN, "test_config_cache_generation")
	if err := db.WithContext(ctx).Exec(`
CREATE TABLE system_config_cache_generation (
 namespace varchar(128) NOT NULL, scope_key varchar(128) NOT NULL, generation bigint NOT NULL,
 created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL,
 CONSTRAINT pk_system_config_cache_generation PRIMARY KEY(namespace, scope_key));
CREATE TABLE system_config_cache_outbox (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 namespace varchar(128) NOT NULL, scope_key varchar(128) NOT NULL, generation bigint NOT NULL,
 attempts integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL,
 locked_until timestamptz, lock_token varchar(64), last_error varchar(512) NOT NULL DEFAULT '',
 published_at timestamptz, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL,
 CONSTRAINT uq_system_config_cache_outbox_generation UNIQUE(namespace, scope_key, generation));
INSERT INTO system_config_cache_generation VALUES ('system.setting','global',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
`).Error; err != nil {
		t.Fatal(err)
	}
	return db, ctx
}

func TestAdvanceTxRollsBackWithBusinessTransaction(t *testing.T) {
	db, ctx := openGenerationDatabase(t)
	repository := NewRepository(db)
	scope := mustGenerationScope(t)
	sentinel := errors.New("business transaction failed")

	err := db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if _, err := repository.AdvanceTx(ctx, tx, scope, 1, time.Now().UTC()); err != nil {
			return err
		}
		return sentinel
	})
	if !errors.Is(err, sentinel) {
		t.Fatalf("transaction error = %v want sentinel", err)
	}
	current, err := repository.Current(ctx, scope)
	if err != nil || current != 1 {
		t.Fatalf("generation after rollback = %d,%v want 1", current, err)
	}
	assertGenerationOutboxCount(t, db, ctx, 0)
}

func TestAdvanceTxRejectsExpectedMismatch(t *testing.T) {
	db, ctx := openGenerationDatabase(t)
	repository := NewRepository(db)
	scope := mustGenerationScope(t)

	err := db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		_, err := repository.AdvanceTx(ctx, tx, scope, 2, time.Now().UTC())
		return err
	})
	if !errors.Is(err, ErrGenerationChanged) {
		t.Fatalf("advance mismatch error = %v want ErrGenerationChanged", err)
	}
	current, err := repository.Current(ctx, scope)
	if err != nil || current != 1 {
		t.Fatalf("generation after mismatch = %d,%v want 1", current, err)
	}
	assertGenerationOutboxCount(t, db, ctx, 0)
}

func TestOutboxClaimExpiryRequiresFreshToken(t *testing.T) {
	db, ctx := openGenerationDatabase(t)
	repository := NewRepository(db)
	seedGenerationOutbox(t, db, ctx, 2, 4)
	now := time.Now().UTC()

	first, err := repository.ClaimPending(ctx, 50, "token-a", now, time.Minute)
	if err != nil || len(first) != 3 {
		t.Fatalf("first claim = %d,%v want 3", len(first), err)
	}
	for index, event := range first {
		if event.Generation != int64(index+2) || event.Attempts != 1 || event.LockToken != "token-a" {
			t.Fatalf("first claim event[%d] = %+v", index, event)
		}
	}
	locked, err := repository.ClaimPending(ctx, 50, "token-b", now.Add(time.Second), time.Minute)
	if err != nil || len(locked) != 0 {
		t.Fatalf("locked claim = %d,%v want 0", len(locked), err)
	}

	reclaimed, err := repository.ClaimPending(ctx, 50, "token-b", now.Add(2*time.Minute), time.Minute)
	if err != nil || len(reclaimed) != 3 {
		t.Fatalf("reclaim = %d,%v want 3", len(reclaimed), err)
	}
	for _, event := range reclaimed {
		if event.Attempts != 2 || event.LockToken != "token-b" {
			t.Fatalf("reclaim event = %+v", event)
		}
	}
	if err := repository.MarkPublished(ctx, first[0].ID, "token-a", now.Add(2*time.Minute)); !errors.Is(err, ErrOutboxClaimLost) {
		t.Fatalf("expired publish error = %v want ErrOutboxClaimLost", err)
	}
	if err := repository.Reschedule(ctx, first[1].ID, "token-a", "dependency-unavailable", now.Add(3*time.Minute), now.Add(2*time.Minute)); !errors.Is(err, ErrOutboxClaimLost) {
		t.Fatalf("expired reschedule error = %v want ErrOutboxClaimLost", err)
	}
	if err := repository.MarkPublished(ctx, reclaimed[0].ID, "token-b", now.Add(2*time.Minute)); err != nil {
		t.Fatalf("fresh publish error = %v", err)
	}
	remaining, err := repository.ClaimPending(ctx, 50, "token-c", now.Add(3*time.Minute), time.Minute)
	if err != nil || len(remaining) != 2 {
		t.Fatalf("claim after publish = %d,%v want 2", len(remaining), err)
	}
}

func TestClaimPendingTwoWorkersUseSkipLockedWithoutOverlap(t *testing.T) {
	db, ctx := openGenerationDatabase(t)
	repository := NewRepository(db)
	seedGenerationOutbox(t, db, ctx, 2, 56)
	now := time.Now().UTC()

	var mutex sync.Mutex
	claimedIDs := make(map[int64]int)
	var waitGroup sync.WaitGroup
	for _, token := range []string{"worker-a", "worker-b"} {
		waitGroup.Add(1)
		go func(token string) {
			defer waitGroup.Done()
			events, err := repository.ClaimPending(ctx, 50, token, now, time.Minute)
			if err != nil {
				t.Errorf("claim %s: %v", token, err)
				return
			}
			mutex.Lock()
			defer mutex.Unlock()
			for _, event := range events {
				claimedIDs[event.ID]++
			}
		}(token)
	}
	waitGroup.Wait()

	if len(claimedIDs) != 55 {
		t.Fatalf("distinct claimed events = %d want 55", len(claimedIDs))
	}
	for id, count := range claimedIDs {
		if count != 1 {
			t.Fatalf("event %d claimed %d times", id, count)
		}
	}
	extra, err := repository.ClaimPending(ctx, 50, "worker-c", now, time.Minute)
	if err != nil || len(extra) != 0 {
		t.Fatalf("claim after full lock = %d,%v want 0", len(extra), err)
	}
}

func TestClaimPendingRejectsInvalidBounds(t *testing.T) {
	db, ctx := openGenerationDatabase(t)
	repository := NewRepository(db)
	now := time.Now().UTC()

	cases := []struct {
		name  string
		claim func() error
	}{
		{"zero limit", func() error { _, err := repository.ClaimPending(ctx, 0, "token", now, time.Minute); return err }},
		{"over limit", func() error { _, err := repository.ClaimPending(ctx, 51, "token", now, time.Minute); return err }},
		{"empty token", func() error { _, err := repository.ClaimPending(ctx, 10, " ", now, time.Minute); return err }},
		{"invalid lease", func() error {
			_, err := repository.ClaimPending(ctx, 10, "token", now, 0)
			return err
		}},
	}
	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			if err := test.claim(); err == nil {
				t.Fatal("ClaimPending accepted an invalid bound")
			}
		})
	}
}

func seedGenerationOutbox(t *testing.T, db *gorm.DB, ctx context.Context, first, last int64) {
	t.Helper()
	seededAt := time.Now().UTC().Add(-time.Minute)
	if err := db.WithContext(ctx).Exec(
		`INSERT INTO system_config_cache_outbox (
			namespace, scope_key, generation, attempts, available_at, created_at, updated_at
		 ) SELECT 'system.setting', 'global', g, 0, ?, ?, ? FROM generate_series(?::int, ?::int) AS g`,
		seededAt, seededAt, seededAt, first, last).Error; err != nil {
		t.Fatalf("seed outbox: %v", err)
	}
}

func assertGenerationOutboxCount(t *testing.T, db *gorm.DB, ctx context.Context, want int64) {
	t.Helper()
	var count int64
	if err := db.WithContext(ctx).Raw(`SELECT count(*) FROM system_config_cache_outbox`).Scan(&count).Error; err != nil {
		t.Fatal(err)
	}
	if count != want {
		t.Fatalf("outbox count = %d want %d", count, want)
	}
}

func assertGenerationCount(t *testing.T, db *gorm.DB, ctx context.Context, want int64) {
	t.Helper()
	var count int64
	if err := db.WithContext(ctx).Raw(`SELECT count(*) FROM system_config_cache_generation`).Scan(&count).Error; err != nil {
		t.Fatal(err)
	}
	if count != want {
		t.Fatalf("generation count = %d want %d", count, want)
	}
}

func TestInitializeTxCreatesGenerationAndOutboxOnce(t *testing.T) {
	db, ctx := openGenerationDatabase(t)
	repository := NewRepository(db)
	scope := initializeScope(t, "storage.cosconfig", "10")
	now := time.Now().UTC()

	var event Event
	if err := db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		created, err := repository.InitializeTx(ctx, tx, scope, now)
		if err != nil {
			return err
		}
		event = created
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	if event.Generation != 1 || event.ID < 1 || event.Scope != scope {
		t.Fatalf("event=%+v", event)
	}
	if current, err := repository.Current(ctx, scope); err != nil || current != 1 {
		t.Fatalf("generation=%d err=%v want 1", current, err)
	}
	assertGenerationCount(t, db, ctx, 2)
	assertGenerationOutboxCount(t, db, ctx, 1)

	// 重复初始化必须报告已存在，且不覆盖、不推进既有行。
	err := db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		_, err := repository.InitializeTx(ctx, tx, scope, now.Add(time.Minute))
		return err
	})
	if !errors.Is(err, ErrGenerationAlreadyExists) {
		t.Fatalf("duplicate initialize error = %v want ErrGenerationAlreadyExists", err)
	}
	if current, err := repository.Current(ctx, scope); err != nil || current != 1 {
		t.Fatalf("generation after duplicate = %d err=%v want 1", current, err)
	}
	assertGenerationCount(t, db, ctx, 2)
	assertGenerationOutboxCount(t, db, ctx, 1)
}

func TestInitializeTxRollsBackWithCallerTransaction(t *testing.T) {
	db, ctx := openGenerationDatabase(t)
	repository := NewRepository(db)
	scope := initializeScope(t, "storage.cosconfig", "11")
	sentinel := errors.New("business transaction failed")

	err := db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if _, err := repository.InitializeTx(ctx, tx, scope, time.Now().UTC()); err != nil {
			return err
		}
		return sentinel
	})
	if !errors.Is(err, sentinel) {
		t.Fatalf("transaction error = %v want sentinel", err)
	}
	if _, err := repository.Current(ctx, scope); !errors.Is(err, ErrGenerationRowMissing) {
		t.Fatalf("generation row survived caller rollback: %v", err)
	}
	assertGenerationCount(t, db, ctx, 1)
	assertGenerationOutboxCount(t, db, ctx, 0)
}

func TestInitializeTxRejectsInvalidInput(t *testing.T) {
	db, ctx := openGenerationDatabase(t)
	repository := NewRepository(db)
	valid := initializeScope(t, "storage.cosconfig", "12")

	cases := []struct {
		name string
		call func() error
	}{
		{"nil transaction", func() error {
			_, err := repository.InitializeTx(ctx, nil, valid, time.Now().UTC())
			return err
		}},
		{"invalid scope", func() error {
			_, err := repository.InitializeTx(ctx, db, Scope{Namespace: "Storage", ScopeKey: "12"}, time.Now().UTC())
			return err
		}},
		{"empty scope key", func() error {
			_, err := repository.InitializeTx(ctx, db, Scope{Namespace: "storage.cosconfig"}, time.Now().UTC())
			return err
		}},
		{"zero time", func() error {
			_, err := repository.InitializeTx(ctx, db, valid, time.Time{})
			return err
		}},
	}
	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			if err := test.call(); err == nil {
				t.Fatal("InitializeTx accepted invalid input")
			}
		})
	}
	assertGenerationCount(t, db, ctx, 1)
	assertGenerationOutboxCount(t, db, ctx, 0)
}

// 隔离 fixture 的 outbox 表没有外键，因此可以构造"同 scope 同代 outbox 已存在"的事实异常：
// 初始化必须上抛该冲突，而不能伪装成 ErrGenerationAlreadyExists（那会让调用方以为是自己建的行）。
func TestInitializeTxSurfacesOutboxConflictAsAnomaly(t *testing.T) {
	db, ctx := openGenerationDatabase(t)
	repository := NewRepository(db)
	scope := initializeScope(t, "storage.cosconfig", "13")
	now := time.Now().UTC()
	if err := db.WithContext(ctx).Exec(
		`INSERT INTO system_config_cache_outbox (namespace, scope_key, generation, attempts, available_at, created_at, updated_at)
		 VALUES (?, ?, 1, 0, ?, ?, ?)`,
		scope.Namespace, scope.ScopeKey, now, now, now).Error; err != nil {
		t.Fatal(err)
	}

	err := db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		_, err := repository.InitializeTx(ctx, tx, scope, now)
		return err
	})
	if err == nil {
		t.Fatal("InitializeTx accepted an outbox conflict")
	}
	if errors.Is(err, ErrGenerationAlreadyExists) {
		t.Fatalf("outbox conflict was misreported as ErrGenerationAlreadyExists: %v", err)
	}
	if !strings.Contains(err.Error(), "system_config_cache_outbox") {
		t.Fatalf("error = %v want outbox constraint context", err)
	}
	if _, err := repository.Current(ctx, scope); !errors.Is(err, ErrGenerationRowMissing) {
		t.Fatalf("generation row survived conflicting transaction: %v", err)
	}
	assertGenerationOutboxCount(t, db, ctx, 1)
}

func TestInitializeTxConcurrentInstancesProduceExactlyOneWinner(t *testing.T) {
	db, ctx := openGenerationDatabase(t)
	second := openSecondGenerationInstance(t, db)
	scope := initializeScope(t, "storage.cosconfig", "20")
	now := time.Now().UTC()

	instances := []*gorm.DB{db, second}
	results := make([]error, len(instances))
	start := make(chan struct{})
	var waitGroup sync.WaitGroup
	for index, instance := range instances {
		waitGroup.Add(1)
		go func(index int, instance *gorm.DB) {
			defer waitGroup.Done()
			<-start
			results[index] = instance.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
				_, err := NewRepository(instance).InitializeTx(ctx, tx, scope, now)
				return err
			})
		}(index, instance)
	}
	close(start)
	waitGroup.Wait()

	winners, conflicts := 0, 0
	for _, err := range results {
		switch {
		case err == nil:
			winners++
		case errors.Is(err, ErrGenerationAlreadyExists):
			conflicts++
		default:
			t.Fatalf("unexpected concurrent initialize error: %v", err)
		}
	}
	if winners != 1 || conflicts != 1 {
		t.Fatalf("winners=%d conflicts=%d want 1/1", winners, conflicts)
	}
	if current, err := NewRepository(db).Current(ctx, scope); err != nil || current != 1 {
		t.Fatalf("generation=%d err=%v want 1", current, err)
	}
	assertGenerationCount(t, db, ctx, 2)
	assertGenerationOutboxCount(t, db, ctx, 1)
}

func initializeScope(t *testing.T, namespace, scopeKey string) Scope {
	t.Helper()
	scope, err := NewScope(namespace, scopeKey)
	if err != nil {
		t.Fatal(err)
	}
	return scope
}

// openSecondGenerationInstance 在同一隔离 schema 上再开一个独立连接池，模拟第二个 API 实例。
func openSecondGenerationInstance(t *testing.T, db *gorm.DB) *gorm.DB {
	t.Helper()
	var schema string
	if err := db.WithContext(context.Background()).Raw(`SELECT current_schema()`).Scan(&schema).Error; err != nil {
		t.Fatal(err)
	}
	if strings.TrimSpace(schema) == "" {
		t.Fatal("current schema is empty")
	}
	settings := loadIntegrationSettings(t)
	pgxConfig, err := pgx.ParseConfig(settings.PostgresDSN)
	if err != nil {
		t.Fatal(err)
	}
	pgxConfig.RuntimeParams["search_path"] = schema
	sqlDB := stdlib.OpenDB(*pgxConfig)
	if err := sqlDB.PingContext(context.Background()); err != nil {
		_ = sqlDB.Close()
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = sqlDB.Close() })
	second, err := gorm.Open(postgres.New(postgres.Config{Conn: sqlDB}), &gorm.Config{DisableAutomaticPing: true})
	if err != nil {
		t.Fatal(err)
	}
	return second
}
