package sms

import (
	"context"
	"crypto/sha256"
	"errors"
	"fmt"
	"os"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	projectconfig "admin/server/internal/config"
	"admin/server/internal/database/testschema"
	projectredis "admin/server/internal/redis"
	cachegeneration "admin/server/internal/shared/cacheGeneration"
	"github.com/joho/godotenv"
	"gorm.io/gorm"
)

func openSMSRuntimeRedis(t *testing.T) *projectredis.Client {
	t.Helper()
	if testing.Short() {
		t.Skip("Redis integration")
	}
	if err := godotenv.Load("../../../../.env"); err != nil && !os.IsNotExist(err) {
		t.Fatal(err)
	}
	settings, err := projectconfig.LoadWorker(os.LookupEnv)
	if err != nil {
		t.Fatal(err)
	}
	client, err := projectredis.Open(context.Background(), settings.RedisURL)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = client.Close() })
	return client
}

func openSMSGenerationDatabase(t *testing.T) (*gorm.DB, context.Context) {
	t.Helper()
	if err := godotenv.Load("../../../../.env"); err != nil && !os.IsNotExist(err) {
		t.Fatal(err)
	}
	settings, err := projectconfig.LoadWorker(os.LookupEnv)
	if err != nil {
		t.Fatal(err)
	}
	database, ctx := testschema.Open(t, settings.PostgresDSN, "test_sms_runtime_generation")
	if err := database.WithContext(ctx).Exec(`
CREATE TABLE system_config_cache_generation(
 namespace varchar(128) NOT NULL, scope_key varchar(128) NOT NULL, generation bigint NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(namespace,scope_key));
CREATE TABLE system_config_cache_outbox(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 namespace varchar(128) NOT NULL, scope_key varchar(128) NOT NULL, generation bigint NOT NULL,
 attempts integer NOT NULL DEFAULT 0, available_at timestamptz NOT NULL DEFAULT now(),
 locked_until timestamptz, lock_token varchar(64), last_error varchar(512) NOT NULL DEFAULT '',
 published_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(namespace,scope_key,generation),
 FOREIGN KEY(namespace,scope_key) REFERENCES system_config_cache_generation(namespace,scope_key));
INSERT INTO system_config_cache_generation(namespace,scope_key,generation) VALUES ('message.sms','global',1);`).Error; err != nil {
		t.Fatal(err)
	}
	return database, ctx
}

func newSMSCacheTestStore(t *testing.T, database *gorm.DB, client *projectredis.Client) *RuntimeCache {
	t.Helper()
	keys := smsCacheTestKeys(t)
	if err := client.DeleteMany(context.Background(), keys); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = client.DeleteMany(context.Background(), keys) })
	cache := NewRuntimeCache(client)
	cache.SetGenerations(cachegeneration.NewRepository(database), cachegeneration.NewStore(client))
	generation, err := cache.generations.Current(context.Background(), smsGenerationScope)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := cache.states.Reconcile(context.Background(), smsGenerationScope, generation); err != nil {
		t.Fatal(err)
	}
	return cache
}

func secondSMSCacheTestStore(database *gorm.DB, client *projectredis.Client) *RuntimeCache {
	cache := NewRuntimeCache(client)
	cache.SetGenerations(cachegeneration.NewRepository(database), cachegeneration.NewStore(client))
	return cache
}

func smsCacheTestKeys(t *testing.T) []string {
	t.Helper()
	stateKey := cachegeneration.StateKey(smsGenerationScope)
	keys := []string{stateKey}
	variants := []string{runtimeSnapshotVariant}
	for _, scene := range []string{"login", "forget", "bind_phone", "change_password"} {
		variants = append(variants, "readiness:"+scene)
	}
	for generation := int64(1); generation <= 8; generation++ {
		for _, variant := range variants {
			snapshot, err := cachegeneration.SnapshotKey(smsGenerationScope, generation, variant)
			if err != nil {
				t.Fatal(err)
			}
			fill, err := cachegeneration.FillKey(smsGenerationScope, generation, variant)
			if err != nil {
				t.Fatal(err)
			}
			keys = append(keys, snapshot)
			keys = append(keys, cacheFillKeys(stateKey, fill)...)
		}
	}
	for _, variant := range variants {
		keys = append(keys, cacheFillKeys(stateKey, "repair:"+variant)...)
	}
	return keys
}

func cacheFillKeys(scope, target string) []string {
	scopeHash := sha256.Sum256([]byte(scope))
	targetHash := sha256.Sum256([]byte(target))
	prefix := fmt.Sprintf("cachefill:{%x}:", scopeHash[:8])
	return []string{fmt.Sprintf("%skey:%x", prefix, targetHash), prefix + "slots", prefix + "starts"}
}

func runtimeFactsForCacheTest() RuntimeFacts {
	return factsOf(validRuntimeSnapshotForTest())
}

func TestRuntimeCacheTwoInstancesLoadPostgresOnceAndKeepHotReadsInRedis(t *testing.T) {
	database, _ := openSMSGenerationDatabase(t)
	firstClient := openSMSRuntimeRedis(t)
	secondClient := openSMSRuntimeRedis(t)
	first := newSMSCacheTestStore(t, database, firstClient)
	second := secondSMSCacheTestStore(database, secondClient)
	var loads atomic.Int32
	loaderEntered := make(chan struct{})
	contenderWaited := make(chan struct{})
	releaseLoader := make(chan struct{})
	var signalContender sync.Once
	for _, cache := range []*RuntimeCache{first, second} {
		cache.wait = func(ctx context.Context, duration time.Duration) error {
			signalContender.Do(func() { close(contenderWaited) })
			return waitForSMSCache(ctx, duration)
		}
	}
	loader := func(ctx context.Context) (RuntimeFacts, error) {
		if loads.Add(1) == 1 {
			close(loaderEntered)
		}
		select {
		case <-ctx.Done():
			return RuntimeFacts{}, ctx.Err()
		case <-releaseLoader:
			return runtimeFactsForCacheTest(), nil
		}
	}
	errorsFound := make(chan error, 2)
	var wait sync.WaitGroup
	stores := []*RuntimeCache{first, second}
	for index := 0; index < 2; index++ {
		wait.Add(1)
		go func(worker int) {
			defer wait.Done()
			facts, err := stores[worker%len(stores)].Load(context.Background(), loader)
			if err != nil || !facts.Configured {
				errorsFound <- fmt.Errorf("load=%+v err=%w", facts, err)
			}
		}(index)
	}
	select {
	case <-loaderEntered:
	case <-time.After(2 * time.Second):
		t.Fatal("no cache fill leader entered the loader")
	}
	select {
	case <-contenderWaited:
	case <-time.After(2 * time.Second):
		t.Fatal("second cache instance did not contend for the fill lease")
	}
	close(releaseLoader)
	wait.Wait()
	close(errorsFound)
	for err := range errorsFound {
		t.Fatal(err)
	}
	if loads.Load() != 1 {
		t.Fatalf("source loads=%d, want 1", loads.Load())
	}
	for index := 0; index < 50; index++ {
		if _, err := stores[index%len(stores)].Load(context.Background(), loader); err != nil {
			t.Fatal(err)
		}
	}
	if loads.Load() != 1 {
		t.Fatalf("hot reads reached source: %d", loads.Load())
	}
}

func TestRuntimeAndReadinessUseOneGenerationWithSeparateVariants(t *testing.T) {
	database, ctx := openSMSGenerationDatabase(t)
	client := openSMSRuntimeRedis(t)
	cache := newSMSCacheTestStore(t, database, client)
	if _, err := cache.Load(ctx, func(context.Context) (RuntimeFacts, error) { return runtimeFactsForCacheTest(), nil }); err != nil {
		t.Fatal(err)
	}
	ready, err := cache.LoadReadiness(ctx, "login", func(context.Context) (VerifyCodeReadiness, error) {
		return VerifyCodeReadiness{Ready: true, TTLMinutes: 5}, nil
	})
	if err != nil || !ready.Ready || ready.TTLMinutes != 5 {
		t.Fatalf("readiness=%+v err=%v", ready, err)
	}
	runtimeKey, _ := cachegeneration.SnapshotKey(smsGenerationScope, 1, runtimeSnapshotVariant)
	readinessKey, _ := cachegeneration.SnapshotKey(smsGenerationScope, 1, "readiness:login")
	if _, found, err := client.GetString(ctx, runtimeKey); err != nil || !found {
		t.Fatalf("runtime snapshot found=%v err=%v", found, err)
	}
	if _, found, err := client.GetString(ctx, readinessKey); err != nil || !found {
		t.Fatalf("readiness snapshot found=%v err=%v", found, err)
	}
}

func TestRuntimeCacheCorruptSnapshotIsRebuilt(t *testing.T) {
	database, ctx := openSMSGenerationDatabase(t)
	client := openSMSRuntimeRedis(t)
	cache := newSMSCacheTestStore(t, database, client)
	key, _ := cachegeneration.SnapshotKey(smsGenerationScope, 1, runtimeSnapshotVariant)
	corrupt := `{"schemaVersion":1,"generation":1,"configured":true}`
	if err := client.SetString(ctx, key, corrupt, time.Minute); err != nil {
		t.Fatal(err)
	}
	var loads atomic.Int32
	facts, err := cache.Load(ctx, func(context.Context) (RuntimeFacts, error) {
		loads.Add(1)
		return runtimeFactsForCacheTest(), nil
	})
	if err != nil || !facts.Configured {
		t.Fatalf("rebuilt facts=%+v err=%v", facts, err)
	}
	if loads.Load() != 1 {
		t.Fatalf("source loads=%d, want 1", loads.Load())
	}
	raw, found, err := client.GetString(ctx, key)
	if err != nil || !found || raw == corrupt {
		t.Fatalf("rebuilt snapshot found=%v err=%v raw=%s", found, err, raw)
	}
}

func TestRuntimeCacheRedisFailureFailsClosedWithoutPostgres(t *testing.T) {
	database, ctx := openSMSGenerationDatabase(t)
	client := openSMSRuntimeRedis(t)
	cache := secondSMSCacheTestStore(database, client)
	if err := client.Close(); err != nil {
		t.Fatal(err)
	}
	var loads atomic.Int32
	if _, err := cache.Load(ctx, func(context.Context) (RuntimeFacts, error) {
		loads.Add(1)
		return runtimeFactsForCacheTest(), nil
	}); err == nil {
		t.Fatal("closed Redis client was accepted")
	}
	if loads.Load() != 0 {
		t.Fatalf("Redis failure fell back to PostgreSQL %d times", loads.Load())
	}
}

func TestRuntimeCacheDropsOldFillWhenGenerationAdvances(t *testing.T) {
	database, ctx := openSMSGenerationDatabase(t)
	client := openSMSRuntimeRedis(t)
	cache := newSMSCacheTestStore(t, database, client)
	var loads atomic.Int32
	facts, err := cache.Load(ctx, func(loadContext context.Context) (RuntimeFacts, error) {
		if loads.Add(1) == 1 {
			result, advanceErr := advanceSMSGeneration(loadContext, database, 1)
			if advanceErr != nil {
				return RuntimeFacts{}, advanceErr
			}
			if _, reconcileErr := cache.states.Reconcile(loadContext, smsGenerationScope, result.Generation); reconcileErr != nil {
				return RuntimeFacts{}, reconcileErr
			}
		}
		return runtimeFactsForCacheTest(), nil
	})
	if err != nil || !facts.Configured {
		t.Fatalf("facts after generation advance=%+v err=%v", facts, err)
	}
	oldKey, _ := cachegeneration.SnapshotKey(smsGenerationScope, 1, runtimeSnapshotVariant)
	if _, found, err := client.GetString(ctx, oldKey); err != nil || found {
		t.Fatalf("old snapshot found=%v err=%v", found, err)
	}
	newKey, _ := cachegeneration.SnapshotKey(smsGenerationScope, 2, runtimeSnapshotVariant)
	if _, found, err := client.GetString(ctx, newKey); err != nil || !found {
		t.Fatalf("new snapshot found=%v err=%v", found, err)
	}
}

func TestRuntimeMutationNoOpRestoresReadyWithoutAdvancingGeneration(t *testing.T) {
	database, ctx := openSMSGenerationDatabase(t)
	cache := newSMSCacheTestStore(t, database, openSMSRuntimeRedis(t))
	if err := cache.Mutate(ctx, func(context.Context, int64) (cachegeneration.MutationResult, error) {
		return cachegeneration.MutationResult{}, nil
	}); err != nil {
		t.Fatal(err)
	}
	assertSMSGenerationState(t, ctx, database, cache, 1)
	if count := smsOutboxCount(t, ctx, database, false); count != 0 {
		t.Fatalf("no-op outbox rows=%d, want 0", count)
	}
}

func TestRuntimeMutationPublishFailureReturnsBusinessSuccessAndLeavesOutboxPending(t *testing.T) {
	database, ctx := openSMSGenerationDatabase(t)
	client := openSMSRuntimeRedis(t)
	cache := newSMSCacheTestStore(t, database, client)
	err := cache.Mutate(ctx, func(writeContext context.Context, expected int64) (cachegeneration.MutationResult, error) {
		result, advanceErr := advanceSMSGeneration(writeContext, database, expected)
		if advanceErr != nil {
			return cachegeneration.MutationResult{}, advanceErr
		}
		if closeErr := client.Close(); closeErr != nil {
			return cachegeneration.MutationResult{}, closeErr
		}
		return result, nil
	})
	if err != nil {
		t.Fatalf("committed mutation returned Redis publication failure: %v", err)
	}
	generation, err := cachegeneration.NewRepository(database).Current(ctx, smsGenerationScope)
	if err != nil || generation != 2 {
		t.Fatalf("PostgreSQL generation=%d err=%v, want 2", generation, err)
	}
	if count := smsOutboxCount(t, ctx, database, false); count != 1 {
		t.Fatalf("pending outbox rows=%d, want 1", count)
	}
	cleanupClient := openSMSRuntimeRedis(t)
	if err := cleanupClient.DeleteMany(context.Background(), smsCacheTestKeys(t)); err != nil {
		t.Fatal(err)
	}
}

func TestRuntimeMutationRetryBudgetIsBounded(t *testing.T) {
	database, ctx := openSMSGenerationDatabase(t)
	cache := newSMSCacheTestStore(t, database, openSMSRuntimeRedis(t))
	blockingLease, err := cache.states.Acquire(ctx, smsGenerationScope, 1)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = blockingLease.Rollback(context.Background()) })

	now := time.Unix(0, 0)
	waits := 0
	callbackCalls := 0
	cache.now = func() time.Time { return now }
	cache.wait = func(context.Context, time.Duration) error {
		waits++
		now = now.Add(smsWaitStep)
		return nil
	}
	err = cache.Mutate(ctx, func(context.Context, int64) (cachegeneration.MutationResult, error) {
		callbackCalls++
		return cachegeneration.MutationResult{}, nil
	})
	if !errors.Is(err, cachegeneration.ErrUpdating) {
		t.Fatalf("mutation error=%v, want ErrUpdating", err)
	}
	if waits != 25 || callbackCalls != 0 {
		t.Fatalf("waits=%d callback calls=%d, want 25 and 0", waits, callbackCalls)
	}
}

func advanceSMSGeneration(ctx context.Context, database *gorm.DB, expected int64) (cachegeneration.MutationResult, error) {
	result := cachegeneration.MutationResult{}
	err := database.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		event, err := cachegeneration.NewRepository(database).AdvanceTx(ctx, tx, smsGenerationScope, expected, time.Now().UTC())
		if err != nil {
			return err
		}
		result = cachegeneration.MutationResult{Changed: true, Generation: event.Generation, OutboxID: event.ID}
		return nil
	})
	return result, err
}

func assertSMSGenerationState(t *testing.T, ctx context.Context, database *gorm.DB, cache *RuntimeCache, want int64) {
	t.Helper()
	generation, err := cachegeneration.NewRepository(database).Current(ctx, smsGenerationScope)
	if err != nil || generation != want {
		t.Fatalf("PostgreSQL generation=%d err=%v, want %d", generation, err, want)
	}
	state, found, err := cache.states.Read(ctx, smsGenerationScope)
	if err != nil || !found || state.State != cachegeneration.StateReady || state.Generation != want {
		t.Fatalf("Redis state=%+v found=%v err=%v, want ready %d", state, found, err, want)
	}
}

func smsOutboxCount(t *testing.T, ctx context.Context, database *gorm.DB, published bool) int64 {
	t.Helper()
	condition := "published_at IS NULL"
	if published {
		condition = "published_at IS NOT NULL"
	}
	var count int64
	if err := database.WithContext(ctx).Raw(`SELECT count(*) FROM system_config_cache_outbox WHERE namespace = ? AND scope_key = ? AND `+condition,
		smsGenerationScope.Namespace, smsGenerationScope.ScopeKey).Scan(&count).Error; err != nil {
		t.Fatal(err)
	}
	return count
}
