package log

import (
	"context"
	"errors"
	"os"
	"strings"
	"sync"
	"testing"
	"time"

	"admin/server/internal/config"
	"admin/server/internal/database/testschema"
	logverification "admin/server/internal/module/message/mail/logVerification"
	"admin/server/internal/secretkey"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/joho/godotenv"
	"gorm.io/gorm"
)

func TestRepositoryKeepsOneActiveChallengePerSourcePlatform(t *testing.T) {
	database, ctx := openRepositoryDatabase(t)
	repository := NewRepository(database)
	challenge := "challenge-1"
	now := time.Now().UTC().Truncate(time.Microsecond)
	type result struct {
		value Model
		err   error
	}
	results := make(chan result, 2)
	var wait sync.WaitGroup
	for range 2 {
		wait.Add(1)
		go func() {
			defer wait.Done()
			value, err := repository.CreatePending(ctx, &Model{
				PlatformID: 1, ChallengeID: &challenge, Scene: "login", TemplateID: 47941,
				ToEmail: "user@example.com", Subject: "subject", Status: "pending", CreatedAt: now, UpdatedAt: now,
			})
			results <- result{value: value, err: err}
		}()
	}
	wait.Wait()
	close(results)
	var created Model
	var uniqueErrors int
	for result := range results {
		if result.err == nil {
			created = result.value
			continue
		}
		var postgresError *pgconn.PgError
		if !errors.As(result.err, &postgresError) || postgresError.Code != "23505" {
			t.Fatalf("create error=%v", result.err)
		}
		uniqueErrors++
	}
	if created.ID < 1 || uniqueErrors != 1 {
		t.Fatalf("created=%+v uniqueErrors=%d", created, uniqueErrors)
	}
	if _, err := repository.CreatePending(ctx, &Model{
		PlatformID: 2, ChallengeID: &challenge, Scene: "login", TemplateID: 47941,
		ToEmail: "user@example.com", Subject: "subject", Status: "pending", CreatedAt: now, UpdatedAt: now,
	}); err != nil {
		t.Fatalf("challenge leaked across source platforms: %v", err)
	}
}

func TestServiceDecryptsVerificationDetailFromSubmodule(t *testing.T) {
	database, ctx := openRepositoryDatabase(t)
	keys, err := secretkey.New(strings.Repeat("s", 64))
	if err != nil {
		t.Fatal(err)
	}
	repository := NewRepository(database)
	verificationRepository := logverification.NewRepository(database)
	now := time.Now().UTC().Truncate(time.Microsecond)
	created, err := repository.CreatePending(ctx, &Model{
		PlatformID: 1, Scene: "login", TemplateID: 47941, ToEmail: "user@example.com",
		Subject: "subject", Status: "sent", CreatedAt: now, UpdatedAt: now,
	})
	if err != nil {
		t.Fatal(err)
	}
	ciphertext, version, err := secretkey.EncryptMailValue(keys.MailEncryptionKey(), "123456")
	if err != nil {
		t.Fatal(err)
	}
	expiresAt := now.Add(5 * time.Minute)
	if err := verificationRepository.Create(ctx, &logverification.Model{
		PlatformID: 1, MailLogID: created.ID, KeyVersion: version,
		CodeCiphertext: ciphertext, ExpiresAt: expiresAt, CreatedAt: now,
	}); err != nil {
		t.Fatal(err)
	}
	detail, err := NewService(repository, verificationRepository, keys).Get(ctx, 1, created.ID)
	if err != nil || detail.VerificationCode != "123456" || detail.VerificationExpiresAt == nil || !detail.VerificationExpiresAt.Equal(expiresAt) {
		t.Fatalf("detail=%+v err=%v", detail, err)
	}
}

func openRepositoryDatabase(t *testing.T) (*gorm.DB, context.Context) {
	t.Helper()
	if testing.Short() {
		t.Skip("PostgreSQL integration")
	}
	_ = godotenv.Load("../../../../../.env")
	settings, err := config.LoadWorker(os.LookupEnv)
	if err != nil {
		t.Fatal(err)
	}
	database, ctx := testschema.Open(t, settings.PostgresDSN, "test_mail_log")
	if err := database.WithContext(ctx).Exec(`
CREATE TABLE message_mail_log(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, platform_id bigint NOT NULL,
 challenge_id varchar(128), user_id bigint, scene varchar(32) NOT NULL, template_id integer NOT NULL,
 to_email varchar(254) NOT NULL, subject varchar(255) NOT NULL, status varchar(16) NOT NULL,
 request_id varchar(128) NOT NULL DEFAULT '', message_id varchar(128) NOT NULL DEFAULT '',
 error_code varchar(128) NOT NULL DEFAULT '', error_summary varchar(512) NOT NULL DEFAULT '',
 latency_ms bigint NOT NULL DEFAULT 0, sent_at timestamptz, created_at timestamptz NOT NULL,
 updated_at timestamptz NOT NULL, deleted_at timestamptz);
CREATE UNIQUE INDEX ux_message_mail_log_platform_challenge_active
 ON message_mail_log(platform_id,challenge_id) WHERE deleted_at IS NULL AND challenge_id IS NOT NULL;
CREATE TABLE message_mail_log_verification(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,platform_id bigint NOT NULL,
 mail_log_id bigint NOT NULL,key_version varchar(16) NOT NULL,code_ciphertext text NOT NULL,
 expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL,deleted_at timestamptz);`).Error; err != nil {
		t.Fatal(err)
	}
	return database, ctx
}
