package template

import (
	"context"
	"os"
	"testing"

	projectconfig "admin/server/internal/config"
	"admin/server/internal/database/testschema"
	"admin/server/internal/shared/yesno"
	"github.com/joho/godotenv"
	"gorm.io/gorm"
)

type countingReadiness struct{ calls int }

func (r *countingReadiness) Mutate(ctx context.Context, change func(context.Context) error) error {
	r.calls++
	return change(ctx)
}

func TestServiceUpdatesGlobalTemplateAndInvalidatesReadinessOnStatus(t *testing.T) {
	database, ctx := openServiceDatabase(t)
	repository := NewRepository(database)
	readiness := &countingReadiness{}
	service := NewService(repository, readiness)

	err := service.Update(ctx, 1, UpdateInput{
		Scene: SceneLogin, Name: "Updated", Subject: "Updated subject", TencentTemplateID: 57999,
		Variables:        map[string]string{"code": "123456", "ttl_minutes": "5"},
		ExampleVariables: map[string]string{"code": "654321", "ttl_minutes": "10"},
	})
	if err != nil {
		t.Fatal(err)
	}
	updated, err := repository.Find(ctx, 1)
	if err != nil || updated.Name != "Updated" || updated.Subject != "Updated subject" || updated.TencentTemplateID != 57999 {
		t.Fatalf("updated=%+v err=%v", updated, err)
	}
	if readiness.calls != 0 {
		t.Fatalf("content-only update invalidated readiness %d times", readiness.calls)
	}
	if err := service.SetStatus(ctx, 1, yesno.No); err != nil {
		t.Fatal(err)
	}
	updated, err = repository.Find(ctx, 1)
	if err != nil || updated.IsEnabled != yesno.No || readiness.calls != 1 {
		t.Fatalf("status=%d readiness=%d err=%v", updated.IsEnabled, readiness.calls, err)
	}
}

func TestVariableValidationRequiresFixedKeys(t *testing.T) {
	valid := map[string]string{"code": "123456", "ttl_minutes": "10"}
	if err := ValidateVariables(valid, true); err != nil {
		t.Fatalf("valid variables rejected: %v", err)
	}
	for name, value := range map[string]map[string]string{
		"missing code": {"ttl_minutes": "10"},
		"missing ttl":  {"code": "123456"},
		"unknown key":  {"code": "123456", "ttl_minutes": "10", "extra": "x"},
		"empty code":   {"code": "", "ttl_minutes": "10"},
	} {
		t.Run(name, func(t *testing.T) {
			if err := ValidateVariables(value, true); err == nil {
				t.Fatal("invalid variables accepted")
			}
		})
	}
}

func openServiceDatabase(t *testing.T) (*gorm.DB, context.Context) {
	t.Helper()
	if testing.Short() {
		t.Skip("PostgreSQL integration")
	}
	_ = godotenv.Load("../../../../../.env")
	settings, err := projectconfig.LoadWorker(os.LookupEnv)
	if err != nil {
		t.Fatal(err)
	}
	database, ctx := testschema.Open(t, settings.PostgresDSN, "test_mail_template")
	if err := database.WithContext(ctx).Exec(`
CREATE TABLE message_mail_template(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,scene varchar(32) NOT NULL,
 name varchar(128) NOT NULL,subject varchar(255) NOT NULL,tencent_template_id integer NOT NULL,
 variables jsonb NOT NULL,example_variables jsonb NOT NULL,is_enabled smallint NOT NULL,
 created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,deleted_at timestamptz);
CREATE UNIQUE INDEX ux_message_mail_template_scene_active ON message_mail_template(scene) WHERE deleted_at IS NULL;
INSERT INTO message_mail_template(scene,name,subject,tencent_template_id,variables,example_variables,is_enabled,created_at,updated_at)
VALUES ('login','Login','Login',47941,'{"code":"123456","ttl_minutes":"5"}','{"code":"123456","ttl_minutes":"5"}',1,now(),now());`).Error; err != nil {
		t.Fatal(err)
	}
	return database, ctx
}
