package template

import (
	"context"
	"errors"
	"os"
	"testing"

	projectconfig "admin/server/internal/config"
	"admin/server/internal/database/testschema"
	"admin/server/internal/shared/cacheGeneration"
	"admin/server/internal/shared/yesno"
	"github.com/joho/godotenv"
	"gorm.io/gorm"
)

type passthroughRuntime struct {
	calls      int
	generation int64
}

func (r *passthroughRuntime) Mutate(ctx context.Context, change func(context.Context, int64) (cachegeneration.MutationResult, error)) error {
	r.calls++
	result, err := change(ctx, r.generation)
	if err == nil && result.Changed {
		r.generation = result.Generation
	}
	return err
}

type runtimeCoordinatorFunc func(context.Context, func(context.Context, int64) (cachegeneration.MutationResult, error)) error

func (f runtimeCoordinatorFunc) Mutate(ctx context.Context, change func(context.Context, int64) (cachegeneration.MutationResult, error)) error {
	return f(ctx, change)
}

func TestServiceUpdatesGlobalTemplateAndInvalidatesReadinessOnStatus(t *testing.T) {
	database, ctx := openServiceDatabase(t)
	repository := configuredRepository(database)
	runtime := &passthroughRuntime{generation: 1}
	service := NewService(repository)
	service.SetRuntimeCoordinator(runtime)

	err := service.Update(ctx, 1, UpdateInput{
		Scene: SceneLogin, Name: "Updated", Subject: "Updated subject", TencentTemplateID: intPointer(57999),
		Content: "<html>{{code}} {{ttl_minutes}}</html>", VariableKeys: []string{"code", "ttl_minutes"},
		ExampleVariables: map[string]string{"code": "654321", "ttl_minutes": "10"},
	})
	if err != nil {
		t.Fatal(err)
	}
	updated, err := repository.Find(ctx, 1)
	if err != nil || updated.Name != "Updated" || updated.Subject != "Updated subject" || updated.TencentTemplateID == nil || *updated.TencentTemplateID != 57999 {
		t.Fatalf("updated=%+v err=%v", updated, err)
	}
	if runtime.calls != 1 {
		t.Fatalf("content-only update mutations = %d", runtime.calls)
	}
	if err := service.SetStatus(ctx, 1, yesno.No); err != nil {
		t.Fatal(err)
	}
	updated, err = repository.Find(ctx, 1)
	if err != nil || updated.IsEnabled != yesno.No || runtime.calls != 2 {
		t.Fatalf("status=%d mutations=%d err=%v", updated.IsEnabled, runtime.calls, err)
	}
}

func TestVariableValidationRequiresVerificationKeys(t *testing.T) {
	valid := map[string]string{"code": "123456", "ttl_minutes": "10"}
	if err := ValidateVariables(valid, true); err != nil {
		t.Fatalf("valid variables rejected: %v", err)
	}
	for name, value := range map[string]map[string]string{
		"missing code": {"ttl_minutes": "10"},
		"missing ttl":  {"code": "123456"},
		"empty code":   {"code": "", "ttl_minutes": "10"},
	} {
		t.Run(name, func(t *testing.T) {
			if err := ValidateVariables(value, true); err == nil {
				t.Fatal("invalid variables accepted")
			}
		})
	}
}

func TestServiceDoesNotUpdateWhenRuntimeInvalidationFails(t *testing.T) {
	database, ctx := openServiceDatabase(t)
	repository := configuredRepository(database)
	service := NewService(repository)
	service.SetRuntimeCoordinator(runtimeCoordinatorFunc(func(context.Context, func(context.Context, int64) (cachegeneration.MutationResult, error)) error {
		return errors.New("redis unavailable")
	}))
	err := service.Update(ctx, 1, UpdateInput{
		Scene: SceneLogin, Name: "Must Not Persist", Subject: "Changed", TencentTemplateID: intPointer(57999),
		Content: "<html>{{code}} {{ttl_minutes}}</html>", VariableKeys: []string{"code", "ttl_minutes"},
		ExampleVariables: map[string]string{"code": "654321", "ttl_minutes": "10"},
	})
	if err == nil {
		t.Fatal("update succeeded while runtime invalidation failed")
	}
	stored, findErr := repository.Find(ctx, 1)
	if findErr != nil || stored.Name != "Login" || stored.TencentTemplateID == nil || *stored.TencentTemplateID != 47941 {
		t.Fatalf("stored template=%+v err=%v", stored, findErr)
	}
}

func openServiceDatabase(t *testing.T) (*gorm.DB, context.Context) {
	t.Helper()
	if testing.Short() {
		t.Skip("PostgreSQL integration")
	}
	_ = godotenv.Load("../../../../../.env")
	settings, err := projectconfig.LoadWorker(os.LookupEnv)
	if err != nil {
		t.Fatal(err)
	}
	database, ctx := testschema.Open(t, settings.PostgresDSN, "test_mail_template")
	if err := database.WithContext(ctx).Exec(`
CREATE TABLE message_mail_template(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,scene varchar(32) NOT NULL,
 name varchar(128) NOT NULL,subject varchar(255) NOT NULL,tencent_template_id integer,
 content text NOT NULL,variable_keys jsonb NOT NULL,example_variables jsonb NOT NULL,is_enabled smallint NOT NULL,
 created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,deleted_at timestamptz);
CREATE UNIQUE INDEX ux_message_mail_template_scene_active ON message_mail_template(scene) WHERE deleted_at IS NULL;
CREATE TABLE system_config_cache_generation(namespace varchar(128) NOT NULL,scope_key varchar(128) NOT NULL,generation bigint NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(namespace,scope_key));
CREATE TABLE system_config_cache_outbox(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,namespace varchar(128) NOT NULL,scope_key varchar(128) NOT NULL,generation bigint NOT NULL,attempts integer NOT NULL DEFAULT 0,available_at timestamptz NOT NULL DEFAULT now(),locked_until timestamptz,lock_token varchar(64),last_error varchar(512) NOT NULL DEFAULT '',published_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(namespace,scope_key,generation),FOREIGN KEY(namespace,scope_key) REFERENCES system_config_cache_generation(namespace,scope_key));
INSERT INTO system_config_cache_generation(namespace,scope_key,generation) VALUES ('message.mail','global',1);
INSERT INTO message_mail_template(scene,name,subject,tencent_template_id,content,variable_keys,example_variables,is_enabled,created_at,updated_at)
VALUES ('login','Login','Login',47941,'<html>{{code}} {{ttl_minutes}}</html>','["code","ttl_minutes"]','{"code":"123456","ttl_minutes":"5"}',1,now(),now());`).Error; err != nil {
		t.Fatal(err)
	}
	return database, ctx
}

func configuredRepository(database *gorm.DB) *Repository {
	repository := NewRepository(database)
	repository.SetGenerations(cachegeneration.NewRepository(database), cachegeneration.Scope{Namespace: "message.mail", ScopeKey: "global"})
	return repository
}

func intPointer(value int) *int { return &value }
