package loginlog

import (
	"os"
	"testing"
	"time"

	"admin/server/internal/config"
	"admin/server/internal/database/testschema"
	"admin/server/internal/shared/yesno"

	"github.com/joho/godotenv"
)

func TestRepositoryKeepsSoftDeletedPlatformVisibleInHistory(t *testing.T) {
	if testing.Short() {
		t.Skip("PostgreSQL integration")
	}
	_ = godotenv.Load("../../../../.env")
	settings, err := config.LoadWorker(os.LookupEnv)
	if err != nil {
		t.Fatal(err)
	}
	database, ctx := testschema.Open(t, settings.PostgresDSN, "test_login_log_platform_history")
	now := time.Now().UTC().Truncate(time.Microsecond)
	if err := database.WithContext(ctx).Exec(`
CREATE TABLE permission_auth_platform(
 id bigint PRIMARY KEY, code varchar(49) NOT NULL, deleted_at timestamptz);
CREATE TABLE user_login_log(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint, session_id bigint,
 platform_id bigint NOT NULL REFERENCES permission_auth_platform(id) ON DELETE RESTRICT,
 login_account varchar(254) NOT NULL, event_type varchar(16) NOT NULL, login_type varchar(32),
 is_success smallint NOT NULL, reason_code varchar(64) NOT NULL, client_ip varchar(64) NOT NULL,
	 user_agent varchar(512) NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);`).Error; err != nil {
		t.Fatal(err)
	}
	if err := database.WithContext(ctx).Exec(
		"INSERT INTO permission_auth_platform(id, code) VALUES (17, 'retired')",
	).Error; err != nil {
		t.Fatal(err)
	}
	if err := database.WithContext(ctx).Exec(`
INSERT INTO user_login_log(platform_id, login_account, event_type, login_type, is_success,
 reason_code, client_ip, user_agent, created_at, updated_at)
VALUES (17, 'user@example.com', 'login', 'email', 1, 'ok', '127.0.0.1', 'test', ?, ?)`, now, now).Error; err != nil {
		t.Fatal(err)
	}
	if err := database.WithContext(ctx).Exec(
		"UPDATE permission_auth_platform SET deleted_at = ? WHERE id = 17", now,
	).Error; err != nil {
		t.Fatal(err)
	}

	items, total, err := NewRepository(database).List(ctx, ListQuery{Page: 1, PageSize: 20})
	if err != nil {
		t.Fatal(err)
	}
	if total != 1 || len(items) != 1 || items[0].Platform != "retired" || items[0].IsSuccess != int16(yesno.Yes) {
		t.Fatalf("history total=%d items=%+v, want one row from retired platform", total, items)
	}
}
