package mail

import (
	"context"
	"os"
	"testing"

	"admin/server/internal/config"
	"admin/server/internal/database/testschema"
	"github.com/joho/godotenv"
	"gorm.io/gorm"
)

func openMailRepositoryDatabase(t *testing.T) (*gorm.DB, context.Context) {
	t.Helper()
	if testing.Short() {
		t.Skip("PostgreSQL integration test")
	}
	_ = godotenv.Load("../../../../.env")
	settings, err := config.LoadWorker(os.LookupEnv)
	if err != nil {
		t.Fatal(err)
	}
	database, ctx := testschema.Open(t, settings.PostgresDSN, "test_mail_repository")
	if err := database.WithContext(ctx).Exec(`
CREATE TABLE message_mail_log (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, platform_id BIGINT NOT NULL,
 challenge_id VARCHAR(128), user_id BIGINT, scene VARCHAR(32) NOT NULL, template_id INTEGER NOT NULL,
 to_email VARCHAR(254) NOT NULL, subject VARCHAR(255) NOT NULL, status VARCHAR(16) NOT NULL,
 request_id VARCHAR(128) NOT NULL DEFAULT '', message_id VARCHAR(128) NOT NULL DEFAULT '',
 error_code VARCHAR(128) NOT NULL DEFAULT '', error_summary VARCHAR(512) NOT NULL DEFAULT '',
 latency_ms BIGINT NOT NULL DEFAULT 0, sent_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL,
 updated_at TIMESTAMPTZ NOT NULL);
CREATE UNIQUE INDEX ux_message_mail_log_platform_challenge
 ON message_mail_log(platform_id, challenge_id) WHERE challenge_id IS NOT NULL;
CREATE TABLE message_mail_log_verification (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 platform_id BIGINT NOT NULL,
 mail_log_id BIGINT NOT NULL,
 key_version VARCHAR(16) NOT NULL,
 code_ciphertext TEXT NOT NULL,
 expires_at TIMESTAMPTZ NOT NULL,
 created_at TIMESTAMPTZ NOT NULL
);
CREATE UNIQUE INDEX ux_message_mail_verification_log ON message_mail_log_verification(mail_log_id);
CREATE TABLE message_mail_rate_limit_policy (
 platform_id BIGINT NOT NULL, policy_key VARCHAR(64) NOT NULL, mode VARCHAR(16) NOT NULL, dimension VARCHAR(64) NOT NULL,
 limit_count INTEGER NOT NULL, window_seconds INTEGER NOT NULL, revision BIGINT NOT NULL DEFAULT 1,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (platform_id, policy_key));
INSERT INTO message_mail_rate_limit_policy (platform_id, policy_key, mode, dimension, limit_count, window_seconds, revision) VALUES
 (1, 'business_email_minute', 'business', 'platform_email', 1, 60, 1),
 (1, 'business_email_10m', 'business', 'platform_email', 5, 600, 1),
 (2, 'business_email_minute', 'business', 'platform_email', 1, 60, 1),
 (2, 'business_email_10m', 'business', 'platform_email', 5, 600, 1);`).Error; err != nil {
		t.Fatal(err)
	}
	return database, ctx
}
