package uploadrule

import (
	"context"
	"errors"
	"os"
	"strings"
	"sync"
	"testing"
	"time"

	"admin/server/internal/config"
	"admin/server/internal/database/testschema"
	"admin/server/internal/shared/apperror"
	"admin/server/internal/shared/yesno"
	"github.com/joho/godotenv"
	"gorm.io/gorm"
)

func TestServiceValidatesTargetsAndAllowsMultipleEnabledRules(t *testing.T) {
	db, ctx := openRuleDatabase(t)
	platformID := insertPlatform(t, db, ctx, "admin", yesno.Yes)
	disabledPlatformID := insertPlatform(t, db, ctx, "disabled", yesno.No)
	configID := insertConfig(t, db, ctx, "main", yesno.Yes, "https://cdn.example.com")
	privateConfigID := insertConfig(t, db, ctx, "private", yesno.Yes, "")
	disabledConfigID := insertConfig(t, db, ctx, "disabled", yesno.No, "")
	service := NewService(NewRepository(db), nil, nil)

	firstID, err := service.Create(ctx, validCreate(platformID, configID, []string{"avatar", "article-cover"}, yesno.Yes))
	if err != nil {
		t.Fatal(err)
	}
	secondID, err := service.Create(ctx, validCreate(platformID, configID, []string{"attachment"}, yesno.Yes))
	if err != nil {
		t.Fatal(err)
	}
	assertEnabledRule(t, db, ctx, platformID, firstID, secondID)
	listed, err := service.List(ctx, ListQuery{Page: 1, PageSize: 20})
	if err != nil || len(listed.List) != 2 || len(listed.List[0].AllowedExtensions) != 1 {
		t.Fatalf("list result = %+v,%v", listed, err)
	}
	if _, err := service.Create(ctx, validCreate(platformID, configID, []string{"attachment"}, yesno.No)); appCode(err) != apperror.CodeConflict {
		t.Fatalf("duplicate code error = %v", err)
	}
	if _, err := service.Create(ctx, validCreate(disabledPlatformID, configID, []string{"disabled-platform"}, yesno.No)); appCode(err) != apperror.CodeConflict {
		t.Fatalf("disabled platform error = %v", err)
	}
	if _, err := service.Create(ctx, validCreate(platformID, disabledConfigID, []string{"disabled-config"}, yesno.No)); appCode(err) != apperror.CodeConflict {
		t.Fatalf("disabled config error = %v", err)
	}
	public := validCreate(platformID, privateConfigID, []string{"public"}, yesno.No)
	public.AccessMode = "public"
	if _, err := service.Create(ctx, public); appCode(err) != apperror.CodeConflict {
		t.Fatalf("public config error = %v", err)
	}
	if err := service.Delete(ctx, secondID); appCode(err) != apperror.CodeConflict {
		t.Fatalf("delete enabled error = %v", err)
	}
	if err := service.UpdateStatus(ctx, secondID, yesno.No); err != nil {
		t.Fatal(err)
	}
	if err := service.UpdateStatus(ctx, firstID, yesno.No); err != nil {
		t.Fatal(err)
	}
	assertEnabledRule(t, db, ctx, platformID)
}

func TestConcurrentEnableAllowsMultipleRules(t *testing.T) {
	db, ctx := openRuleDatabase(t)
	platformID := insertPlatform(t, db, ctx, "admin", yesno.Yes)
	configID := insertConfig(t, db, ctx, "main", yesno.Yes, "")
	service := NewService(NewRepository(db), nil, nil)
	firstID, err := service.Create(ctx, validCreate(platformID, configID, []string{"one"}, yesno.No))
	if err != nil {
		t.Fatal(err)
	}
	secondID, err := service.Create(ctx, validCreate(platformID, configID, []string{"two"}, yesno.No))
	if err != nil {
		t.Fatal(err)
	}

	start := make(chan struct{})
	errorsByCall := make([]error, 2)
	var wait sync.WaitGroup
	for index, id := range []int64{firstID, secondID} {
		wait.Add(1)
		go func(index int, id int64) {
			defer wait.Done()
			<-start
			errorsByCall[index] = service.UpdateStatus(context.Background(), id, yesno.Yes)
		}(index, id)
	}
	close(start)
	wait.Wait()
	for _, err := range errorsByCall {
		if err != nil {
			t.Fatalf("concurrent enable error = %v", err)
		}
	}
	var enabled int64
	if err := db.WithContext(ctx).Model(&Model{}).Where("platform_id = ? AND is_enabled = 1 AND deleted_at IS NULL", platformID).Count(&enabled).Error; err != nil {
		t.Fatal(err)
	}
	if enabled != 2 {
		t.Fatalf("enabled rule count = %d", enabled)
	}
}

func validCreate(platformID, configID int64, codes []string, enabled yesno.Value) CreateInput {
	return CreateInput{PlatformID: platformID, Codes: codes, Name: strings.ToUpper(codes[0]), CosConfigID: configID, MaxFileSizeBytes: 1024, AllowedExtensions: []string{"png"}, AllowedMimeTypes: []string{"image/png"}, AccessMode: "private", IsEnabled: enabled}
}

func openRuleDatabase(t *testing.T) (*gorm.DB, context.Context) {
	t.Helper()
	if testing.Short() {
		t.Skip("PostgreSQL integration test")
	}
	if err := godotenv.Load("../../../../.env"); err != nil && !os.IsNotExist(err) {
		t.Fatal(err)
	}
	settings, err := config.LoadWorker(os.LookupEnv)
	if err != nil {
		t.Fatal(err)
	}
	db, ctx := testschema.Open(t, settings.PostgresDSN, "test_uploadrule")
	if err := db.WithContext(ctx).Exec(`
		CREATE TABLE auth_platform (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code VARCHAR(49) NOT NULL, name VARCHAR(64) NOT NULL, is_enabled SMALLINT NOT NULL, deleted_at TIMESTAMPTZ);
		CREATE TABLE storage_cos_config (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(128) NOT NULL, app_id VARCHAR(32) NOT NULL DEFAULT '', secret_id_ciphertext TEXT NOT NULL DEFAULT '', secret_key_ciphertext TEXT NOT NULL DEFAULT '', bucket VARCHAR(128) NOT NULL DEFAULT '', region VARCHAR(64) NOT NULL DEFAULT '', endpoint VARCHAR(255), bucket_domain VARCHAR(255), is_enabled SMALLINT NOT NULL, remark VARCHAR(512) NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMPTZ);
		CREATE TABLE storage_upload_rule (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, platform_id BIGINT NOT NULL, name VARCHAR(128) NOT NULL, cos_config_id BIGINT NOT NULL, max_file_size_bytes BIGINT NOT NULL, allowed_extensions TEXT[] NOT NULL, allowed_mime_types TEXT[] NOT NULL, access_mode VARCHAR(16) NOT NULL, is_enabled SMALLINT NOT NULL, remark VARCHAR(512) NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMPTZ);
		CREATE TABLE storage_upload_rule_code (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, rule_id BIGINT NOT NULL, platform_id BIGINT NOT NULL, code VARCHAR(64) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMPTZ);
		CREATE UNIQUE INDEX ux_storage_upload_rule_code_platform_code ON storage_upload_rule_code(platform_id, code) WHERE deleted_at IS NULL;
		CREATE INDEX ix_storage_upload_rule_code_rule ON storage_upload_rule_code(rule_id, id) WHERE deleted_at IS NULL;
	`).Error; err != nil {
		t.Fatal(err)
	}
	return db, ctx
}

func insertPlatform(t *testing.T, db *gorm.DB, ctx context.Context, code string, enabled yesno.Value) int64 {
	t.Helper()
	var id int64
	if err := db.WithContext(ctx).Raw("INSERT INTO auth_platform(code,name,is_enabled) VALUES(?,?,?) RETURNING id", code, code, enabled).Scan(&id).Error; err != nil {
		t.Fatal(err)
	}
	return id
}
func insertConfig(t *testing.T, db *gorm.DB, ctx context.Context, name string, enabled yesno.Value, domain string) int64 {
	t.Helper()
	var id int64
	var value any
	if domain != "" {
		value = domain
	}
	if err := db.WithContext(ctx).Raw("INSERT INTO storage_cos_config(name,is_enabled,bucket_domain) VALUES(?,?,?) RETURNING id", name, enabled, value).Scan(&id).Error; err != nil {
		t.Fatal(err)
	}
	return id
}
func assertEnabledRule(t *testing.T, db *gorm.DB, ctx context.Context, platformID int64, wantIDs ...int64) {
	t.Helper()
	var rows []Model
	if err := db.WithContext(ctx).Where("platform_id=? AND is_enabled=1 AND deleted_at IS NULL", platformID).Find(&rows).Error; err != nil {
		t.Fatal(err)
	}
	if len(rows) != len(wantIDs) {
		t.Fatalf("enabled=%+v want=%v", rows, wantIDs)
	}
	for _, wantID := range wantIDs {
		found := false
		for _, row := range rows {
			if row.ID == wantID {
				found = true
				break
			}
		}
		if !found {
			t.Fatalf("enabled=%+v want=%v", rows, wantIDs)
		}
	}
}
func appCode(err error) int {
	var appErr *apperror.Error
	if errors.As(err, &appErr) {
		return appErr.Code
	}
	return 0
}

var _ = time.Now
