package config

import (
	"context"
	"os"
	"strings"
	"testing"

	projectconfig "admin/server/internal/config"
	"admin/server/internal/database/testschema"
	"admin/server/internal/secretkey"
	"admin/server/internal/shared/yesno"
	"github.com/joho/godotenv"
	"gorm.io/gorm"
)

type passthroughReadiness struct{}

func (passthroughReadiness) Mutate(ctx context.Context, change func(context.Context) error) error {
	return change(ctx)
}

func TestServiceSavesOneGlobalConfigAndPreservesOmittedCredentials(t *testing.T) {
	database, ctx := openServiceDatabase(t)
	keys, err := secretkey.New(strings.Repeat("s", 64))
	if err != nil {
		t.Fatal(err)
	}
	service := NewService(NewRepository(database), keys, passthroughReadiness{})
	input := Input{
		SecretID: "secret-id", SecretKey: "secret-key", Region: "ap-guangzhou",
		FromEmail: " Sender@Example.COM ", FromName: "Sender", TTLMinutes: 5, IsEnabled: yesno.Yes,
	}

	created, err := service.Save(ctx, input)
	if err != nil {
		t.Fatal(err)
	}
	if !created.Configured || created.FromEmail != "sender@example.com" || created.TTLMinutes != 5 {
		t.Fatalf("created=%+v", created)
	}
	input.SecretID, input.SecretKey, input.FromName = "", "", "Updated"
	updated, err := service.Save(ctx, input)
	if err != nil {
		t.Fatal(err)
	}
	if !updated.Configured || updated.FromName != "Updated" {
		t.Fatalf("updated=%+v", updated)
	}
	var active int64
	if err := database.WithContext(ctx).Model(&Model{}).Where("deleted_at IS NULL").Count(&active).Error; err != nil || active != 1 {
		t.Fatalf("active configs=%d err=%v", active, err)
	}
	if err := service.Delete(ctx); err != nil {
		t.Fatal(err)
	}
	if value, err := service.Get(ctx); err != nil || value.Configured {
		t.Fatalf("deleted config=%+v err=%v", value, err)
	}
}

func TestNormalizeAddressRejectsDisplayName(t *testing.T) {
	if _, err := normalizeAddress("Admin <admin@example.com>"); err == nil {
		t.Fatal("display-name sender accepted")
	}
	if value, err := normalizeAddress(" Admin@Example.COM "); err != nil || value != "admin@example.com" {
		t.Fatalf("plain sender normalization = %q,%v", value, err)
	}
}

func openServiceDatabase(t *testing.T) (*gorm.DB, context.Context) {
	t.Helper()
	if testing.Short() {
		t.Skip("PostgreSQL integration")
	}
	_ = godotenv.Load("../../../../../.env")
	settings, err := projectconfig.LoadWorker(os.LookupEnv)
	if err != nil {
		t.Fatal(err)
	}
	database, ctx := testschema.Open(t, settings.PostgresDSN, "test_mail_config")
	if err := database.WithContext(ctx).Exec(`
CREATE TABLE message_mail_config(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 secret_id_ciphertext text NOT NULL,secret_key_ciphertext text NOT NULL,
 secret_id_hint varchar(32) NOT NULL,secret_key_hint varchar(32) NOT NULL,
 region varchar(64) NOT NULL,endpoint varchar(255),from_email varchar(254) NOT NULL,
 from_name varchar(128) NOT NULL,reply_to varchar(254),ttl_minutes smallint NOT NULL,
 is_enabled smallint NOT NULL,last_test_at timestamptz,last_test_error varchar(512) NOT NULL DEFAULT '',
 created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL,deleted_at timestamptz);
CREATE UNIQUE INDEX ux_message_mail_config_active_singleton ON message_mail_config((true)) WHERE deleted_at IS NULL;`).Error; err != nil {
		t.Fatal(err)
	}
	return database, ctx
}
