package menu

const (
	PermissionList               = "system:menu:list"
	PermissionCreate             = "system:menu:create"
	PermissionUpdate             = "system:menu:update"
	PermissionDelete             = "system:menu:delete"
	PermissionRoleList           = "system:role:list"
	PermissionRoleCreate         = "system:role:create"
	PermissionRoleUpdate         = "system:role:update"
	PermissionRoleStatus         = "system:role:status"
	PermissionRoleDefault        = "system:role:default"
	PermissionRoleDelete         = "system:role:delete"
	PermissionRoleAuthorize      = "system:role:authorize"
	PermissionUserList           = "system:user:list"
	PermissionUserUpdate         = "system:user:update"
	PermissionUserStatus         = "system:user:status"
	PermissionUserDelete         = "system:user:delete"
	PermissionUserRoles          = "system:user:roles"
	PermissionAuthPlatformList   = "system:auth-platform:list"
	PermissionAuthPlatformCreate = "system:auth-platform:create"
	PermissionAuthPlatformUpdate = "system:auth-platform:update"
	PermissionAuthPlatformStatus = "system:auth-platform:status"
	PermissionAuthPlatformDelete = "system:auth-platform:delete"
	PermissionSessionList        = "system:session:list"
	PermissionSessionRevoke      = "system:session:revoke"
	PermissionOperationLogList   = "system:operation-log:list"
)
