package dictionary

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"runtime"
	"testing"
	"time"

	"admin/server/internal/config"
	"admin/server/internal/database/testschema"
	"admin/server/internal/shared/cacheGeneration"
	"admin/server/internal/shared/yesno"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/joho/godotenv"
	"gorm.io/gorm"
)

func TestMapRepositoryErrorMapsUniqueViolation(t *testing.T) {
	err := mapRepositoryError(&pgconn.PgError{Code: "23505"})
	if !errors.Is(err, ErrConflict) {
		t.Fatalf("mapped error = %v, want ErrConflict", err)
	}
}

func TestMapRepositoryErrorPreservesOtherErrors(t *testing.T) {
	original := errors.New("database unavailable")
	if !errors.Is(mapRepositoryError(original), original) {
		t.Fatal("non-unique repository error was changed")
	}
}

func TestRepositoryUpdateIsAtomicWithGenerationAndNoOpDoesNotAdvance(t *testing.T) {
	h := openDictionaryRepositoryHarness(t)
	dictionary := h.seedDictionary(t, Dictionary{Code: "user.gender", NameZH: "性别", NameEN: "Gender", IsEnabled: yesno.Yes})

	noOp, err := h.repository.Update(h.ctx, dictionary.ID, UpdateInput{NameZH: "性别", NameEN: "Gender"}, 1, h.now)
	if err != nil {
		t.Fatalf("no-op Update() error = %v", err)
	}
	if noOp.Changed {
		t.Fatalf("no-op Update() result = %+v", noOp)
	}
	h.assertGeneration(t, 1, nil)

	changed, err := h.repository.Update(h.ctx, dictionary.ID, UpdateInput{NameZH: "用户性别", NameEN: "User gender"}, 1, h.now.Add(time.Minute))
	if err != nil {
		t.Fatalf("changed Update() error = %v", err)
	}
	if !changed.Changed || changed.Generation != 2 || changed.OutboxID < 1 {
		t.Fatalf("changed Update() result = %+v", changed)
	}
	h.assertGeneration(t, 2, []int64{2})
}

func TestRepositoryGenerationConflictRollsBackBusinessWrite(t *testing.T) {
	h := openDictionaryRepositoryHarness(t)
	dictionary := h.seedDictionary(t, Dictionary{Code: "user.gender", NameZH: "性别", NameEN: "Gender", IsEnabled: yesno.Yes})
	if err := h.db.WithContext(h.ctx).Exec(
		`UPDATE system_config_cache_generation SET generation = 2 WHERE namespace = ? AND scope_key = ?`,
		h.scope.Namespace, h.scope.ScopeKey,
	).Error; err != nil {
		t.Fatal(err)
	}

	_, err := h.repository.Update(h.ctx, dictionary.ID, UpdateInput{NameZH: "不应提交", NameEN: "Must rollback"}, 1, h.now)
	if !errors.Is(err, cachegeneration.ErrGenerationChanged) {
		t.Fatalf("Update() error = %v want ErrGenerationChanged", err)
	}
	row, findErr := h.repository.Find(h.ctx, dictionary.ID)
	if findErr != nil {
		t.Fatal(findErr)
	}
	if row.NameZH != "性别" || row.NameEN != "Gender" {
		t.Fatalf("business row was not rolled back: %+v", row)
	}
	h.assertGeneration(t, 2, nil)
}

func TestRepositoryDeleteChecksBuiltinAndChildrenInsideTransaction(t *testing.T) {
	for _, test := range []struct {
		name     string
		builtin  yesno.Value
		withItem bool
	}{
		{name: "builtin", builtin: yesno.Yes},
		{name: "children", builtin: yesno.No, withItem: true},
	} {
		t.Run(test.name, func(t *testing.T) {
			h := openDictionaryRepositoryHarness(t)
			dictionary := h.seedDictionary(t, Dictionary{Code: "system.fixed", NameZH: "固定", NameEN: "Fixed", IsEnabled: yesno.Yes, IsBuiltin: test.builtin})
			if test.withItem {
				h.seedItem(t, Item{DictionaryID: dictionary.ID, Value: "one", LabelZH: "一", LabelEN: "One", IsEnabled: yesno.Yes})
			}
			if _, err := h.repository.Delete(h.ctx, dictionary.ID, 1, h.now); !errors.Is(err, ErrConflict) {
				t.Fatalf("Delete() error = %v want conflict", err)
			}
			if _, err := h.repository.Find(h.ctx, dictionary.ID); err != nil {
				t.Fatalf("dictionary was deleted after conflict: %v", err)
			}
			h.assertGeneration(t, 1, nil)
		})
	}
}

func TestRepositoryCreateItemLocksAndValidatesParent(t *testing.T) {
	h := openDictionaryRepositoryHarness(t)
	dictionary := h.seedDictionary(t, Dictionary{Code: "user.gender", NameZH: "性别", NameEN: "Gender", IsEnabled: yesno.No})
	item := Item{DictionaryID: dictionary.ID, Value: "male", LabelZH: "男", LabelEN: "Male", IsEnabled: yesno.Yes, CreatedAt: h.now, UpdatedAt: h.now}
	if _, err := h.repository.CreateItem(h.ctx, &item, 1, h.now); !errors.Is(err, ErrConflict) {
		t.Fatalf("CreateItem() error = %v want conflict", err)
	}
	var count int64
	if err := h.db.WithContext(h.ctx).Model(&Item{}).Count(&count).Error; err != nil {
		t.Fatal(err)
	}
	if count != 0 {
		t.Fatalf("item count = %d want 0", count)
	}
	h.assertGeneration(t, 1, nil)
}

type dictionaryRepositoryHarness struct {
	ctx         context.Context
	db          *gorm.DB
	repository  *Repository
	generations *cachegeneration.Repository
	scope       cachegeneration.Scope
	now         time.Time
}

func openDictionaryRepositoryHarness(t *testing.T) dictionaryRepositoryHarness {
	t.Helper()
	settings := loadDictionaryTestSettings(t)
	db, ctx := testschema.Open(t, settings.PostgresDSN, "test_system_dictionary_generation")
	if err := db.WithContext(ctx).Exec(`
CREATE TABLE system_dictionary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(128) NOT NULL,
  name_zh VARCHAR(128) NOT NULL,
  name_en VARCHAR(128) NOT NULL,
  description VARCHAR(512) NOT NULL,
  is_enabled SMALLINT NOT NULL CHECK (is_enabled IN (0, 1)),
  is_builtin SMALLINT NOT NULL CHECK (is_builtin IN (0, 1)),
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX ux_system_dictionary_code_active ON system_dictionary(code) WHERE deleted_at IS NULL;
CREATE TABLE system_dictionary_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dictionary_id BIGINT NOT NULL REFERENCES system_dictionary(id),
  value VARCHAR(128) NOT NULL,
  label_zh VARCHAR(256) NOT NULL,
  label_en VARCHAR(256) NOT NULL,
  sort INTEGER NOT NULL,
  is_enabled SMALLINT NOT NULL CHECK (is_enabled IN (0, 1)),
  is_builtin SMALLINT NOT NULL CHECK (is_builtin IN (0, 1)),
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX ux_system_dictionary_item_value_active ON system_dictionary_item(dictionary_id, value) WHERE deleted_at IS NULL;
CREATE TABLE system_config_cache_generation (
  namespace VARCHAR(128) NOT NULL,
  scope_key VARCHAR(128) NOT NULL,
  generation BIGINT NOT NULL DEFAULT 1 CHECK (generation >= 1),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (namespace, scope_key)
);
CREATE TABLE system_config_cache_outbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  namespace VARCHAR(128) NOT NULL,
  scope_key VARCHAR(128) NOT NULL,
  generation BIGINT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  locked_until TIMESTAMPTZ,
  lock_token VARCHAR(64),
  last_error VARCHAR(512) NOT NULL DEFAULT '',
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (namespace, scope_key, generation),
  FOREIGN KEY (namespace, scope_key) REFERENCES system_config_cache_generation(namespace, scope_key),
  CHECK (published_at IS NULL OR (locked_until IS NULL AND lock_token IS NULL))
);`).Error; err != nil {
		t.Fatal(err)
	}
	scope, err := cachegeneration.NewScope("system.dictionary", "test-"+time.Now().UTC().Format("20060102150405.000000000"))
	if err != nil {
		t.Fatal(err)
	}
	if err := db.WithContext(ctx).Exec(
		`INSERT INTO system_config_cache_generation(namespace, scope_key, generation) VALUES (?, ?, 1)`,
		scope.Namespace, scope.ScopeKey,
	).Error; err != nil {
		t.Fatal(err)
	}
	generations := cachegeneration.NewRepository(db)
	repository := NewRepository(db)
	repository.SetGenerations(generations, scope)
	return dictionaryRepositoryHarness{
		ctx: ctx, db: db, repository: repository, generations: generations, scope: scope,
		now: time.Date(2026, time.September, 17, 0, 0, 0, 0, time.UTC),
	}
}

func (h dictionaryRepositoryHarness) seedDictionary(t *testing.T, value Dictionary) Dictionary {
	t.Helper()
	value.Description = ""
	if value.IsBuiltin != yesno.Yes {
		value.IsBuiltin = yesno.No
	}
	value.CreatedAt = h.now
	value.UpdatedAt = h.now
	if err := h.db.WithContext(h.ctx).Create(&value).Error; err != nil {
		t.Fatal(err)
	}
	return value
}

func (h dictionaryRepositoryHarness) seedItem(t *testing.T, value Item) Item {
	t.Helper()
	if value.IsBuiltin != yesno.Yes {
		value.IsBuiltin = yesno.No
	}
	value.CreatedAt = h.now
	value.UpdatedAt = h.now
	if err := h.db.WithContext(h.ctx).Create(&value).Error; err != nil {
		t.Fatal(err)
	}
	return value
}

func (h dictionaryRepositoryHarness) assertGeneration(t *testing.T, want int64, outbox []int64) {
	t.Helper()
	var generation int64
	if err := h.db.WithContext(h.ctx).Raw(
		`SELECT generation FROM system_config_cache_generation WHERE namespace = ? AND scope_key = ?`,
		h.scope.Namespace, h.scope.ScopeKey,
	).Scan(&generation).Error; err != nil {
		t.Fatal(err)
	}
	if generation != want {
		t.Fatalf("generation = %d want %d", generation, want)
	}
	var got []int64
	if err := h.db.WithContext(h.ctx).Raw(
		`SELECT generation FROM system_config_cache_outbox WHERE namespace = ? AND scope_key = ? ORDER BY generation`,
		h.scope.Namespace, h.scope.ScopeKey,
	).Scan(&got).Error; err != nil {
		t.Fatal(err)
	}
	if len(got) != len(outbox) {
		t.Fatalf("outbox generations = %v want %v", got, outbox)
	}
	for index := range outbox {
		if got[index] != outbox[index] {
			t.Fatalf("outbox generations = %v want %v", got, outbox)
		}
	}
}

func loadDictionaryTestSettings(t *testing.T) config.Worker {
	t.Helper()
	if testing.Short() {
		t.Skip("integration test")
	}
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	repoRoot := filepath.Clean(filepath.Join(filepath.Dir(filename), "..", "..", "..", "..", ".."))
	if err := godotenv.Load(filepath.Join(repoRoot, "server", ".env")); err != nil && !os.IsNotExist(err) {
		t.Fatal(err)
	}
	settings, err := config.LoadWorker(os.LookupEnv)
	if err != nil {
		t.Fatal(err)
	}
	return settings
}
