package cosconfig

import (
	"context"
	"errors"
	"os"
	"testing"
	"time"

	"admin/server/internal/config"
	"admin/server/internal/database/testschema"
	"admin/server/internal/shared/yesno"
	"github.com/joho/godotenv"
	"gorm.io/gorm"
)

func TestRepositoryFiltersConflictsAndAffectedRows(t *testing.T) {
	db, ctx := openConfigDatabase(t)
	repository := NewRepository(db)
	now := time.Now().UTC()
	first := &Model{Name: "Main", AppID: "1250000000", SecretIDCiphertext: "cipher-id", SecretKeyCiphertext: "cipher-key", Bucket: "assets", Region: "ap-guangzhou", IsEnabled: yesno.Yes, Remark: "", CreatedAt: now, UpdatedAt: now}
	if err := repository.Create(ctx, first); err != nil {
		t.Fatal(err)
	}
	duplicate := *first
	duplicate.ID = 0
	duplicate.Name = "main"
	if err := repository.Create(ctx, &duplicate); !errors.Is(err, ErrNameConflict) {
		t.Fatalf("duplicate create error = %v", err)
	}
	total, err := repository.Count(ctx, ListQuery{Keyword: "asset"})
	if err != nil || total != 1 {
		t.Fatalf("count = %d,%v", total, err)
	}
	rows, err := repository.List(ctx, ListQuery{Page: 1, PageSize: 20})
	if err != nil || len(rows) != 1 || rows[0].ID != first.ID {
		t.Fatalf("list = %+v,%v", rows, err)
	}
	if err := repository.Update(ctx, 999, map[string]any{"name": "missing"}); !errors.Is(err, gorm.ErrRecordNotFound) {
		t.Fatalf("missing update error = %v", err)
	}
	if err := repository.MarkDeleted(ctx, 999, now); !errors.Is(err, gorm.ErrRecordNotFound) {
		t.Fatalf("missing delete error = %v", err)
	}
}

func openConfigDatabase(t *testing.T) (*gorm.DB, context.Context) {
	t.Helper()
	if testing.Short() {
		t.Skip("PostgreSQL integration test")
	}
	if err := godotenv.Load("../../../../.env"); err != nil && !os.IsNotExist(err) {
		t.Fatal(err)
	}
	settings, err := config.LoadWorker(os.LookupEnv)
	if err != nil {
		t.Fatal(err)
	}
	db, ctx := testschema.Open(t, settings.PostgresDSN, "test_cosconfig")
	if err := db.WithContext(ctx).Exec(`
		CREATE TABLE storage_cos_config (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR(128) NOT NULL,
			app_id VARCHAR(32) NOT NULL,
			secret_id_ciphertext TEXT NOT NULL,
			secret_key_ciphertext TEXT NOT NULL,
			bucket VARCHAR(128) NOT NULL,
			region VARCHAR(64) NOT NULL,
			endpoint VARCHAR(255),
			bucket_domain VARCHAR(255),
			is_enabled SMALLINT NOT NULL DEFAULT 1 CHECK (is_enabled IN (0, 1)),
			remark VARCHAR(512) NOT NULL DEFAULT '',
			created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
			updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
			deleted_at TIMESTAMPTZ
		);
		CREATE UNIQUE INDEX ux_storage_cos_config_name_active ON storage_cos_config (lower(name)) WHERE deleted_at IS NULL;
		CREATE TABLE storage_upload_rule (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			cos_config_id BIGINT NOT NULL,
			is_enabled SMALLINT NOT NULL DEFAULT 1,
			deleted_at TIMESTAMPTZ
		);
	`).Error; err != nil {
		t.Fatal(err)
	}
	return db, ctx
}
