import {
    Activity,
    Bell,
    Bot,
    BrainCircuit,
    CircleDollarSign,
    Cloud,
    CloudUpload,
    Cpu,
    Database,
    FileStack,
    Folder,
    Gauge,
    HardDrive,
    House,
    Images,
    KeyRound,
    LayoutDashboard,
    ListTree,
    LockKeyhole,
    MessageSquareMore,
    MonitorSmartphone,
    PanelLeft,
    ScrollText,
    Server,
    Settings2,
    ShieldCheck,
    Sparkles,
    UserCog,
    UserCircle,
    UserRound,
    UserRoundCog,
    Users,
    UsersRound,
    WalletCards,
} from 'lucide-vue-next'
import type {Component} from 'vue'

export const menuIcons = {
    'lucide:activity': {component: Activity, label: '活动'},
    'lucide:bell': {component: Bell, label: '通知'},
    'lucide:bot': {component: Bot, label: 'AI 助手'},
    'lucide:brain-circuit': {component: BrainCircuit, label: 'AI 模型'},
    'lucide:circle-dollar-sign': {component: CircleDollarSign, label: '支付'},
    'lucide:cloud': {component: Cloud, label: '云服务'},
    'lucide:cloud-upload': {component: CloudUpload, label: '上传'},
    'lucide:cpu': {component: Cpu, label: '算力'},
    'lucide:database': {component: Database, label: '数据库'},
    'lucide:file-stack': {component: FileStack, label: '文件'},
    'lucide:folder': {component: Folder, label: '目录'},
    'lucide:gauge': {component: Gauge, label: '仪表盘'},
    'lucide:hard-drive': {component: HardDrive, label: '存储'},
    'lucide:house': {component: House, label: '首页'},
    'lucide:images': {component: Images, label: '图片'},
    'lucide:key-round': {component: KeyRound, label: '认证密钥'},
    'lucide:layout-dashboard': {component: LayoutDashboard, label: '控制台'},
    'lucide:list-tree': {component: ListTree, label: '层级列表'},
    'lucide:lock-keyhole': {component: LockKeyhole, label: '安全'},
    'lucide:message-square-more': {component: MessageSquareMore, label: '对话'},
    'lucide:monitor-smartphone': {component: MonitorSmartphone, label: '会话设备'},
    'lucide:panel-left': {component: PanelLeft, label: '菜单'},
    'lucide:scroll-text': {component: ScrollText, label: '操作日志'},
    'lucide:server': {component: Server, label: '服务器'},
    'lucide:settings-2': {component: Settings2, label: '系统设置'},
    'lucide:shield-check': {component: ShieldCheck, label: '权限认证'},
    'lucide:sparkles': {component: Sparkles, label: '智能能力'},
    'lucide:user-cog': {component: UserCog, label: '角色'},
    'lucide:user-circle': {component: UserCircle, label: '个人中心'},
    'lucide:user-round': {component: UserRound, label: '用户'},
    'lucide:user-round-cog': {component: UserRoundCog, label: '用户管理'},
    'lucide:users': {component: Users, label: '用户组'},
    'lucide:users-round': {component: UsersRound, label: '用户与账号'},
    'lucide:wallet-cards': {component: WalletCards, label: '钱包'},
} as const satisfies Record<string, { component: Component; label: string }>

export type MenuIconName = keyof typeof menuIcons

export function isMenuIconName(value: string): value is MenuIconName {
    return Object.prototype.hasOwnProperty.call(menuIcons, value)
}
