BEGIN;

CREATE TABLE IF NOT EXISTS message_notification_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id BIGINT NOT NULL,
    title VARCHAR(128) NOT NULL,
    content_html TEXT NOT NULL,
    summary VARCHAR(256) NOT NULL,
    variant VARCHAR(16) NOT NULL,
    priority VARCHAR(16) NOT NULL,
    link_type VARCHAR(16) NOT NULL,
    link VARCHAR(2048) NOT NULL DEFAULT '',
    audience_type VARCHAR(16) NOT NULL,
    scheduled_at TIMESTAMPTZ NULL,
    audience_max_user_id BIGINT NULL,
    submitted_at TIMESTAMPTZ NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'draft',
    next_user_id BIGINT NOT NULL DEFAULT 0,
    next_batch_no INTEGER NOT NULL DEFAULT 0,
    generated_count BIGINT NOT NULL DEFAULT 0,
    failure_message VARCHAR(512) NULL,
    published_at TIMESTAMPTZ NULL,
    completed_at TIMESTAMPTZ NULL,
    canceled_at TIMESTAMPTZ NULL,
    failed_at TIMESTAMPTZ NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT fk_message_notification_task_platform FOREIGN KEY (platform_id) REFERENCES permission_auth_platform(id) ON DELETE RESTRICT,
    CONSTRAINT fk_message_notification_task_creator FOREIGN KEY (created_by) REFERENCES user_account(id) ON DELETE RESTRICT,
    CONSTRAINT ck_message_notification_task_title CHECK (btrim(title) <> '' AND char_length(title) <= 128),
    CONSTRAINT ck_message_notification_task_content CHECK (char_length(content_html) <= 16384),
    CONSTRAINT ck_message_notification_task_summary CHECK (char_length(summary) <= 256),
    CONSTRAINT ck_message_notification_task_variant CHECK (variant IN ('info','success','warning','error')),
    CONSTRAINT ck_message_notification_task_priority CHECK (priority IN ('normal','urgent')),
    CONSTRAINT ck_message_notification_task_link CHECK ((link_type='none' AND link='') OR (link_type IN ('internal','external') AND btrim(link)<>'')),
    CONSTRAINT ck_message_notification_task_audience CHECK (audience_type IN ('user','role','platform')),
    CONSTRAINT ck_message_notification_task_status CHECK (status IN ('draft','scheduled','queued','processing','completed','failed','canceled')),
    CONSTRAINT ck_message_notification_task_counters CHECK (next_user_id>=0 AND next_batch_no>=0 AND generated_count>=0),
    CONSTRAINT ck_message_notification_task_state CHECK (
        (status='draft' AND submitted_at IS NULL AND audience_max_user_id IS NULL AND published_at IS NULL AND completed_at IS NULL AND canceled_at IS NULL AND failed_at IS NULL AND failure_message IS NULL)
        OR
        (status<>'draft' AND submitted_at IS NOT NULL AND audience_max_user_id IS NOT NULL AND audience_max_user_id>=0
          AND (status<>'scheduled' OR scheduled_at IS NOT NULL)
          AND (status<>'completed' OR completed_at IS NOT NULL)
          AND (status<>'canceled' OR canceled_at IS NOT NULL)
          AND (status<>'failed' OR (failed_at IS NOT NULL AND failure_message IS NOT NULL AND btrim(failure_message)<>'')))
    )
);

CREATE TABLE IF NOT EXISTS message_notification_task_target (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    target_type VARCHAR(16) NOT NULL,
    target_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT fk_message_notification_task_target_task FOREIGN KEY (task_id) REFERENCES message_notification_task(id) ON DELETE CASCADE,
    CONSTRAINT ck_message_notification_task_target_type CHECK (target_type IN ('user','role')),
    CONSTRAINT ck_message_notification_task_target_id CHECK (target_id>0)
);

CREATE TABLE IF NOT EXISTS message_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_id BIGINT NOT NULL,
    source_task_id BIGINT NULL,
    source_type VARCHAR(64) NOT NULL,
    source_key VARCHAR(128) NOT NULL,
    audience_type VARCHAR(16) NOT NULL,
    audience_max_user_id BIGINT NOT NULL,
    title VARCHAR(128) NOT NULL,
    content_html TEXT NOT NULL,
    summary VARCHAR(256) NOT NULL,
    variant VARCHAR(16) NOT NULL,
    priority VARCHAR(16) NOT NULL,
    link_type VARCHAR(16) NOT NULL,
    link VARCHAR(2048) NOT NULL DEFAULT '',
    published_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_message_notification_platform FOREIGN KEY (platform_id) REFERENCES permission_auth_platform(id) ON DELETE RESTRICT,
    CONSTRAINT fk_message_notification_source_task FOREIGN KEY (source_task_id) REFERENCES message_notification_task(id) ON DELETE SET NULL,
    CONSTRAINT ck_message_notification_source CHECK (source_type ~ '^[a-z][a-z0-9]*(\.[a-z][a-z0-9]*)*$' AND btrim(source_key)<>''),
    CONSTRAINT ck_message_notification_audience CHECK (audience_type IN ('targeted','platform') AND audience_max_user_id>=0),
    CONSTRAINT ck_message_notification_content CHECK (btrim(title)<>'' AND char_length(title)<=128 AND char_length(content_html)<=16384 AND char_length(summary)<=256),
    CONSTRAINT ck_message_notification_variant CHECK (variant IN ('info','success','warning','error')),
    CONSTRAINT ck_message_notification_priority CHECK (priority IN ('normal','urgent')),
    CONSTRAINT ck_message_notification_link CHECK ((link_type='none' AND link='') OR (link_type IN ('internal','external') AND btrim(link)<>''))
);

CREATE TABLE IF NOT EXISTS message_notification_recipient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL,
    platform_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    read_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT fk_message_notification_recipient_notification FOREIGN KEY (notification_id) REFERENCES message_notification(id) ON DELETE CASCADE,
    CONSTRAINT fk_message_notification_recipient_platform FOREIGN KEY (platform_id) REFERENCES permission_auth_platform(id) ON DELETE RESTRICT,
    CONSTRAINT fk_message_notification_recipient_user FOREIGN KEY (user_id) REFERENCES user_account(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS message_notification_broadcast_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL,
    platform_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    read_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT fk_message_notification_broadcast_notification FOREIGN KEY (notification_id) REFERENCES message_notification(id) ON DELETE CASCADE,
    CONSTRAINT fk_message_notification_broadcast_platform FOREIGN KEY (platform_id) REFERENCES permission_auth_platform(id) ON DELETE RESTRICT,
    CONSTRAINT fk_message_notification_broadcast_user FOREIGN KEY (user_id) REFERENCES user_account(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS message_notification_mailbox_state (
    platform_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    read_through_notification_id BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (platform_id,user_id),
    CONSTRAINT fk_message_notification_mailbox_platform FOREIGN KEY (platform_id) REFERENCES permission_auth_platform(id) ON DELETE RESTRICT,
    CONSTRAINT fk_message_notification_mailbox_user FOREIGN KEY (user_id) REFERENCES user_account(id) ON DELETE RESTRICT,
    CONSTRAINT ck_message_notification_mailbox_watermark CHECK (read_through_notification_id>=0)
);

CREATE TABLE IF NOT EXISTS realtime_event (
    sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    dedup_key VARCHAR(256) NOT NULL,
    platform_id BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    target_type VARCHAR(16) NOT NULL,
    target_user_id BIGINT NULL,
    audience_max_user_id BIGINT NULL,
    payload JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_realtime_event_platform FOREIGN KEY (platform_id) REFERENCES permission_auth_platform(id) ON DELETE RESTRICT,
    CONSTRAINT fk_realtime_event_user FOREIGN KEY (target_user_id) REFERENCES user_account(id) ON DELETE RESTRICT,
    CONSTRAINT ck_realtime_event_type CHECK (btrim(event_type)<>''),
    CONSTRAINT ck_realtime_event_target CHECK ((target_type='user' AND target_user_id IS NOT NULL AND target_user_id>0 AND audience_max_user_id IS NULL) OR (target_type='platform' AND target_user_id IS NULL AND audience_max_user_id IS NOT NULL AND audience_max_user_id>=0)),
    CONSTRAINT ck_realtime_event_payload CHECK (jsonb_typeof(payload)='object')
);

CREATE TABLE IF NOT EXISTS realtime_event_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_sequence BIGINT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL,
    locked_until TIMESTAMPTZ NULL,
    lock_token VARCHAR(64) NULL,
    published_at TIMESTAMPTZ NULL,
    last_error VARCHAR(512) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_realtime_event_outbox_event FOREIGN KEY (event_sequence) REFERENCES realtime_event(sequence) ON DELETE CASCADE,
    CONSTRAINT ck_realtime_event_outbox_attempts CHECK (attempts>=0),
    CONSTRAINT ck_realtime_event_outbox_lock CHECK ((locked_until IS NULL)=(lock_token IS NULL)),
    CONSTRAINT ck_realtime_event_outbox_published CHECK (published_at IS NULL OR (locked_until IS NULL AND lock_token IS NULL))
);

CREATE TABLE IF NOT EXISTS realtime_retention_state (
    platform_id BIGINT PRIMARY KEY,
    deleted_through_sequence BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_realtime_retention_platform FOREIGN KEY (platform_id) REFERENCES permission_auth_platform(id) ON DELETE RESTRICT,
    CONSTRAINT ck_realtime_retention_watermark CHECK (deleted_through_sequence>=0)
);

CREATE TABLE IF NOT EXISTS message_notification_dispatch_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    batch_no INTEGER NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL,
    locked_until TIMESTAMPTZ NULL,
    lock_token VARCHAR(64) NULL,
    published_at TIMESTAMPTZ NULL,
    last_error VARCHAR(512) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_message_notification_dispatch_task FOREIGN KEY (task_id) REFERENCES message_notification_task(id) ON DELETE CASCADE,
    CONSTRAINT ck_message_notification_dispatch_counters CHECK (batch_no>=0 AND attempts>=0),
    CONSTRAINT ck_message_notification_dispatch_lock CHECK ((locked_until IS NULL)=(lock_token IS NULL)),
    CONSTRAINT ck_message_notification_dispatch_published CHECK (published_at IS NULL OR (locked_until IS NULL AND lock_token IS NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_message_notification_source ON message_notification(platform_id,source_type,source_key);
CREATE UNIQUE INDEX IF NOT EXISTS ux_message_notification_source_task ON message_notification(source_task_id) WHERE source_task_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_message_notification_task_target_active ON message_notification_task_target(task_id,target_type,target_id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_message_notification_recipient ON message_notification_recipient(notification_id,user_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_message_notification_broadcast_state ON message_notification_broadcast_state(notification_id,user_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_realtime_event_event_id ON realtime_event(event_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_realtime_event_dedup_key ON realtime_event(dedup_key);
CREATE UNIQUE INDEX IF NOT EXISTS ux_realtime_event_outbox_event ON realtime_event_outbox(event_sequence);
CREATE UNIQUE INDEX IF NOT EXISTS ux_message_notification_dispatch_batch ON message_notification_dispatch_outbox(task_id,batch_no);
CREATE INDEX IF NOT EXISTS ix_message_notification_task_due ON message_notification_task(status,scheduled_at,id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_message_notification_task_platform_list ON message_notification_task(platform_id,created_at DESC,id DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_message_notification_task_creator_list ON message_notification_task(created_by,created_at DESC,id DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_message_notification_recipient_mailbox ON message_notification_recipient(platform_id,user_id,notification_id DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_message_notification_recipient_unread ON message_notification_recipient(platform_id,user_id,notification_id DESC) WHERE deleted_at IS NULL AND read_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_message_notification_platform_mailbox ON message_notification(platform_id,id DESC) WHERE audience_type='platform';
CREATE INDEX IF NOT EXISTS ix_realtime_event_user_resume ON realtime_event(platform_id,target_user_id,sequence) WHERE target_type='user';
CREATE INDEX IF NOT EXISTS ix_realtime_event_platform_resume ON realtime_event(platform_id,sequence) WHERE target_type='platform';
CREATE INDEX IF NOT EXISTS ix_realtime_event_retention ON realtime_event(occurred_at,sequence);
CREATE INDEX IF NOT EXISTS ix_realtime_event_outbox_pending ON realtime_event_outbox(available_at,id) WHERE published_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_message_notification_dispatch_pending ON message_notification_dispatch_outbox(available_at,id) WHERE published_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_permission_user_role_role_history_cursor ON permission_user_role(role_id,user_id,created_at,deleted_at);

DO $migration$
DECLARE
    admin_platform_id BIGINT;
    message_directory_id BIGINT;
    notification_page_id BIGINT;
    task_page_id BIGINT;
    admin_count INTEGER;
    directory_count INTEGER;
    changed_rows INTEGER;
    setting_changed BOOLEAN := FALSE;
    menu_changed BOOLEAN := FALSE;
    affected_role_ids BIGINT[] := ARRAY[]::BIGINT[];
    role_row RECORD;
    action_row RECORD;
    setting_row RECORD;
    next_generation BIGINT;
BEGIN
    SELECT count(*),min(id) INTO admin_count,admin_platform_id FROM permission_auth_platform WHERE code='admin' AND is_enabled=1 AND deleted_at IS NULL;
    IF admin_count<>1 THEN RAISE EXCEPTION 'expected exactly one active Admin platform'; END IF;

    SELECT count(*),min(id) INTO directory_count,message_directory_id FROM permission_menu WHERE platform_id=admin_platform_id AND code='message' AND menu_type='directory' AND is_enabled=1 AND deleted_at IS NULL;
    IF directory_count<>1 THEN RAISE EXCEPTION 'expected exactly one active Admin message directory'; END IF;

    FOR setting_row IN SELECT * FROM (VALUES
        ('message.notification.retention_days',180,30,3650,'站内通知保留天数'),
        ('realtime.event.retention_days',7,1,30,'实时事件保留天数')
    ) AS settings(setting_key,default_value,min_value,max_value,description)
    LOOP
        IF EXISTS (SELECT 1 FROM system_setting WHERE setting_key=setting_row.setting_key AND deleted_at IS NULL) THEN
            IF EXISTS (SELECT 1 FROM system_setting WHERE setting_key=setting_row.setting_key AND deleted_at IS NULL AND (value !~ '^[0-9]+$' OR value::NUMERIC<>trunc(value::NUMERIC) OR value::NUMERIC<setting_row.min_value OR value::NUMERIC>setting_row.max_value)) THEN
                RAISE EXCEPTION 'invalid existing setting %',setting_row.setting_key;
            END IF;
            UPDATE system_setting SET value_type=2,is_enabled=1,is_builtin=1,description=setting_row.description,updated_at=CURRENT_TIMESTAMP
            WHERE setting_key=setting_row.setting_key AND deleted_at IS NULL
              AND (value_type<>2 OR is_enabled<>1 OR is_builtin<>1 OR description<>setting_row.description);
            GET DIAGNOSTICS changed_rows=ROW_COUNT;
            setting_changed := setting_changed OR changed_rows>0;
        ELSE
            INSERT INTO system_setting(setting_key,value,value_type,description,is_enabled,is_builtin,created_at,updated_at)
            VALUES(setting_row.setting_key,setting_row.default_value::TEXT,2,setting_row.description,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
            setting_changed := TRUE;
        END IF;
    END LOOP;

    IF setting_changed THEN
        UPDATE system_config_cache_generation SET generation=generation+1,updated_at=CURRENT_TIMESTAMP
        WHERE namespace='system.setting' AND scope_key='global' RETURNING generation INTO next_generation;
        IF next_generation IS NULL THEN RAISE EXCEPTION 'system.setting/global generation is missing'; END IF;
        INSERT INTO system_config_cache_outbox(namespace,scope_key,generation,attempts,available_at,last_error,created_at,updated_at)
        VALUES('system.setting','global',next_generation,0,CURRENT_TIMESTAMP,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
    END IF;

    IF EXISTS (SELECT 1 FROM permission_menu WHERE platform_id=admin_platform_id AND deleted_at IS NULL AND path='/message/notification' AND code<>'message:notification:view')
       OR EXISTS (SELECT 1 FROM permission_menu WHERE platform_id=admin_platform_id AND deleted_at IS NULL AND component_path='message/notification' AND code<>'message:notification:view') THEN
        RAISE EXCEPTION 'notification page path is occupied';
    END IF;
    IF EXISTS (SELECT 1 FROM permission_menu WHERE platform_id=admin_platform_id AND code='message:notification:view' AND deleted_at IS NULL AND NOT (menu_type='page' AND parent_id IS NULL AND name='通知中心' AND i18n_key='navigation.messageNotification' AND path='/message/notification' AND component_path='message/notification' AND icon='lucide:bell' AND sort_order=0 AND is_enabled=1 AND is_hidden=1)) THEN
        RAISE EXCEPTION 'incompatible menu node message:notification:view';
    END IF;
    SELECT id INTO notification_page_id FROM permission_menu WHERE platform_id=admin_platform_id AND code='message:notification:view' AND deleted_at IS NULL;
    IF notification_page_id IS NULL THEN
        INSERT INTO permission_menu(platform_id,parent_id,menu_type,name,code,i18n_key,path,component_path,icon,sort_order,is_enabled,is_hidden,created_at,updated_at)
        VALUES(admin_platform_id,NULL,'page','通知中心','message:notification:view','navigation.messageNotification','/message/notification','message/notification','lucide:bell',0,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
        RETURNING id INTO notification_page_id;
        menu_changed := TRUE;
    END IF;

    FOR action_row IN SELECT * FROM (VALUES
        ('message:notification:list','查看个人通知',10),
        ('message:notification:read','标记个人通知已读',20),
        ('message:notification:delete','删除个人通知',30)
    ) AS actions(code,name,sort_order)
    LOOP
        IF EXISTS (SELECT 1 FROM permission_menu WHERE platform_id=admin_platform_id AND code=action_row.code AND deleted_at IS NULL AND NOT (menu_type='action' AND parent_id=notification_page_id AND name=action_row.name AND i18n_key IS NULL AND path IS NULL AND component_path IS NULL AND icon IS NULL AND sort_order=action_row.sort_order AND is_enabled=1 AND is_hidden=1)) THEN
            RAISE EXCEPTION 'incompatible menu node %',action_row.code;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM permission_menu WHERE platform_id=admin_platform_id AND code=action_row.code AND deleted_at IS NULL) THEN
            INSERT INTO permission_menu(platform_id,parent_id,menu_type,name,code,sort_order,is_enabled,is_hidden,created_at,updated_at)
            VALUES(admin_platform_id,notification_page_id,'action',action_row.name,action_row.code,action_row.sort_order,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
            menu_changed := TRUE;
        END IF;
    END LOOP;

    IF EXISTS (SELECT 1 FROM permission_menu WHERE platform_id=admin_platform_id AND deleted_at IS NULL AND path='/message/notificationTask' AND code<>'message:notificationTask:view')
       OR EXISTS (SELECT 1 FROM permission_menu WHERE platform_id=admin_platform_id AND deleted_at IS NULL AND component_path='message/notificationTask' AND code<>'message:notificationTask:view') THEN
        RAISE EXCEPTION 'notification task page path is occupied';
    END IF;
    IF EXISTS (SELECT 1 FROM permission_menu WHERE platform_id=admin_platform_id AND code='message:notificationTask:view' AND deleted_at IS NULL AND NOT (menu_type='page' AND parent_id=message_directory_id AND name='通知任务' AND i18n_key='navigation.messageNotificationTask' AND path='/message/notificationTask' AND component_path='message/notificationTask' AND icon='lucide:bell' AND sort_order=30 AND is_enabled=1 AND is_hidden=0)) THEN
        RAISE EXCEPTION 'incompatible menu node message:notificationTask:view';
    END IF;
    SELECT id INTO task_page_id FROM permission_menu WHERE platform_id=admin_platform_id AND code='message:notificationTask:view' AND deleted_at IS NULL;
    IF task_page_id IS NULL THEN
        INSERT INTO permission_menu(platform_id,parent_id,menu_type,name,code,i18n_key,path,component_path,icon,sort_order,is_enabled,is_hidden,created_at,updated_at)
        VALUES(admin_platform_id,message_directory_id,'page','通知任务','message:notificationTask:view','navigation.messageNotificationTask','/message/notificationTask','message/notificationTask','lucide:bell',30,1,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
        RETURNING id INTO task_page_id;
        menu_changed := TRUE;
    END IF;

    FOR action_row IN SELECT * FROM (VALUES
        ('message:notificationTask:list','查看通知任务',10),('message:notificationTask:detail','查看通知任务详情',20),
        ('message:notificationTask:create','创建通知任务',30),('message:notificationTask:update','编辑通知任务',40),
        ('message:notificationTask:delete','删除通知任务',50),('message:notificationTask:submit','提交通知任务',60),
        ('message:notificationTask:cancel','取消通知任务',70),('message:notificationTask:copy','复制通知任务',80)
    ) AS actions(code,name,sort_order)
    LOOP
        IF EXISTS (SELECT 1 FROM permission_menu WHERE platform_id=admin_platform_id AND code=action_row.code AND deleted_at IS NULL AND NOT (menu_type='action' AND parent_id=task_page_id AND name=action_row.name AND i18n_key IS NULL AND path IS NULL AND component_path IS NULL AND icon IS NULL AND sort_order=action_row.sort_order AND is_enabled=1 AND is_hidden=1)) THEN
            RAISE EXCEPTION 'incompatible menu node %',action_row.code;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM permission_menu WHERE platform_id=admin_platform_id AND code=action_row.code AND deleted_at IS NULL) THEN
            INSERT INTO permission_menu(platform_id,parent_id,menu_type,name,code,sort_order,is_enabled,is_hidden,created_at,updated_at)
            VALUES(admin_platform_id,task_page_id,'action',action_row.name,action_row.code,action_row.sort_order,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
            menu_changed := TRUE;
        END IF;
    END LOOP;

    FOR role_row IN SELECT id FROM permission_role WHERE is_enabled=1 AND deleted_at IS NULL ORDER BY id
    LOOP
        changed_rows := 0;
        INSERT INTO permission_role_menu(role_id,menu_id,created_at,updated_at)
        SELECT role_row.id,m.id,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP
        FROM permission_menu m
        WHERE m.platform_id=admin_platform_id AND m.deleted_at IS NULL
          AND m.code IN ('message:notification:view','message:notification:list','message:notification:read','message:notification:delete')
          AND NOT EXISTS (SELECT 1 FROM permission_role_menu rm WHERE rm.role_id=role_row.id AND rm.menu_id=m.id AND rm.deleted_at IS NULL);
        GET DIAGNOSTICS changed_rows=ROW_COUNT;
        IF changed_rows>0 THEN affected_role_ids:=array_append(affected_role_ids,role_row.id); END IF;
    END LOOP;

    IF cardinality(affected_role_ids)>0 THEN
        UPDATE permission_access_version av SET version=av.version+1,updated_at=CURRENT_TIMESTAMP
        FROM user_account u
        WHERE u.id=av.user_id AND u.is_enabled=1 AND u.deleted_at IS NULL
          AND EXISTS (SELECT 1 FROM permission_user_role ur WHERE ur.user_id=av.user_id AND ur.role_id=ANY(affected_role_ids) AND ur.deleted_at IS NULL);
    END IF;

    IF menu_changed THEN
        UPDATE permission_auth_platform SET menu_version=menu_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=admin_platform_id;
    END IF;
END
$migration$;

COMMIT;
