BEGIN;
CREATE TABLE IF NOT EXISTS system_mail_config (id BIGSERIAL PRIMARY KEY, platform_id BIGINT NOT NULL REFERENCES auth_platform(id), secret_id_ciphertext TEXT NOT NULL, secret_key_ciphertext TEXT NOT NULL, secret_id_hint VARCHAR(32) NOT NULL DEFAULT '', secret_key_hint VARCHAR(32) NOT NULL DEFAULT '', region VARCHAR(64) NOT NULL, endpoint VARCHAR(255), from_email VARCHAR(254) NOT NULL, from_name VARCHAR(128) NOT NULL, reply_to VARCHAR(254), ttl_minutes SMALLINT NOT NULL CHECK (ttl_minutes BETWEEN 1 AND 60), is_enabled SMALLINT NOT NULL DEFAULT 0 CHECK (is_enabled IN (0,1)), last_test_at TIMESTAMPTZ, last_test_error VARCHAR(512) NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS system_mail_template (id BIGSERIAL PRIMARY KEY, platform_id BIGINT NOT NULL REFERENCES auth_platform(id), scene VARCHAR(32) NOT NULL CHECK (scene IN ('login','forget','bind_email','change_password')), name VARCHAR(128) NOT NULL, subject VARCHAR(255) NOT NULL, tencent_template_id INTEGER NOT NULL, variables JSONB NOT NULL, example_variables JSONB NOT NULL, is_enabled SMALLINT NOT NULL DEFAULT 1 CHECK (is_enabled IN (0,1)), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS system_mail_log (id BIGSERIAL PRIMARY KEY, platform_id BIGINT NOT NULL REFERENCES auth_platform(id), challenge_id VARCHAR(128), user_id BIGINT, scene VARCHAR(32) NOT NULL, template_id INTEGER NOT NULL, to_email VARCHAR(254) NOT NULL, subject VARCHAR(255) NOT NULL, status VARCHAR(16) NOT NULL CHECK (status IN ('pending','sent','failed')), request_id VARCHAR(128) NOT NULL DEFAULT '', message_id VARCHAR(128) NOT NULL DEFAULT '', error_code VARCHAR(128) NOT NULL DEFAULT '', error_summary VARCHAR(512) NOT NULL DEFAULT '', latency_ms BIGINT NOT NULL DEFAULT 0, sent_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMPTZ, UNIQUE (id, platform_id));
CREATE TABLE IF NOT EXISTS system_mail_log_verification (id BIGSERIAL PRIMARY KEY, platform_id BIGINT NOT NULL REFERENCES auth_platform(id), mail_log_id BIGINT NOT NULL, key_version VARCHAR(16) NOT NULL, code_ciphertext TEXT NOT NULL, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMPTZ, FOREIGN KEY (mail_log_id, platform_id) REFERENCES system_mail_log(id, platform_id));
CREATE TABLE IF NOT EXISTS system_mail_recipient_rule (id BIGSERIAL PRIMARY KEY, platform_id BIGINT NOT NULL REFERENCES auth_platform(id), scope VARCHAR(16) NOT NULL CHECK (scope IN ('email','domain')), pattern VARCHAR(254) NOT NULL, action VARCHAR(16) NOT NULL CHECK (action IN ('allow','deny')), name VARCHAR(128) NOT NULL, remark VARCHAR(512) NOT NULL DEFAULT '', is_enabled SMALLINT NOT NULL DEFAULT 1 CHECK (is_enabled IN (0,1)), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TIMESTAMPTZ);
CREATE UNIQUE INDEX IF NOT EXISTS ux_system_mail_config_platform_active ON system_mail_config(platform_id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_system_mail_template_platform_scene_active ON system_mail_template(platform_id,scene) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_system_mail_rule_platform_scope_pattern_action_active ON system_mail_recipient_rule(platform_id,scope,pattern,action) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_system_mail_log_platform_challenge_active ON system_mail_log(platform_id,challenge_id) WHERE deleted_at IS NULL AND challenge_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_system_mail_verification_log_active ON system_mail_log_verification(mail_log_id) WHERE deleted_at IS NULL;
INSERT INTO system_mail_template(platform_id,scene,name,subject,tencent_template_id,variables,example_variables,is_enabled)
SELECT p.id,v.scene,v.name,v.subject,v.template_id,v.variables::jsonb,v.variables::jsonb,1 FROM auth_platform p CROSS JOIN (VALUES ('login','邮箱验证码登录','登录验证码',47941,'{"code":"123456","ttl_minutes":"10"}'),('forget','找回密码','找回密码验证码',47942,'{"code":"123456","ttl_minutes":"10"}'),('bind_email','绑定/换绑邮箱','绑定邮箱验证码',47943,'{"code":"123456","ttl_minutes":"10"}'),('change_password','验证码改密','修改密码验证码',47944,'{"code":"123456","ttl_minutes":"10"}')) v(scene,name,subject,template_id,variables) WHERE p.code='admin' AND p.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM system_mail_template t WHERE t.platform_id=p.id AND t.scene=v.scene AND t.deleted_at IS NULL);
COMMIT;
