-- 统一配置缓存代际协议第一阶段 forward migration（唯一入口见同名 .ps1）。
-- 幂等：两表使用 CREATE TABLE IF NOT EXISTS；seed 使用 ON CONFLICT DO NOTHING；
-- RBAC 菜单按 code 严格核验形状，仅在实际变化时对每个受影响平台递增一次 menu_version。
-- 不迁移 permission_auth_platform.menu_version/policy_version、permission_access_version.version；
-- 不自动授予任何角色。

BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';

-- 1. 先锁定并核验 Admin 平台与 system directory（与菜单服务的平台行锁协议一致）。
DO $$
DECLARE
  admin_platform_id BIGINT;
  system_menu_id BIGINT;
BEGIN
  SELECT id INTO admin_platform_id
  FROM permission_auth_platform
  WHERE code = 'admin' AND deleted_at IS NULL AND is_enabled = 1
  FOR UPDATE;
  IF admin_platform_id IS NULL THEN
    RAISE EXCEPTION 'active Admin platform is required';
  END IF;

  SELECT id INTO system_menu_id
  FROM permission_menu
  WHERE platform_id = admin_platform_id
    AND code = 'system' AND menu_type = 'directory' AND deleted_at IS NULL
  FOR UPDATE;
  IF system_menu_id IS NULL THEN
    RAISE EXCEPTION 'active system directory is required';
  END IF;
END $$;

-- 2. generation 与 outbox 持久事实表。
CREATE TABLE IF NOT EXISTS system_config_cache_generation (
    namespace VARCHAR(128) NOT NULL,
    scope_key VARCHAR(128) NOT NULL,
    generation BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_system_config_cache_generation PRIMARY KEY (namespace, scope_key),
    CONSTRAINT ck_system_config_cache_generation_namespace
        CHECK (namespace ~ '^[a-z][a-z0-9]*(\.[a-z][a-z0-9]*)*$'),
    CONSTRAINT ck_system_config_cache_generation_scope_key
        CHECK (scope_key ~ '^[a-zA-Z0-9][a-zA-Z0-9._:-]{0,127}$'),
    CONSTRAINT ck_system_config_cache_generation_value CHECK (generation >= 1)
);

CREATE TABLE IF NOT EXISTS system_config_cache_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    namespace VARCHAR(128) NOT NULL,
    scope_key VARCHAR(128) NOT NULL,
    generation BIGINT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_until TIMESTAMPTZ,
    lock_token VARCHAR(64),
    last_error VARCHAR(512) NOT NULL DEFAULT '',
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_system_config_cache_outbox_generation UNIQUE (namespace, scope_key, generation),
    CONSTRAINT fk_system_config_cache_outbox_generation
        FOREIGN KEY (namespace, scope_key)
        REFERENCES system_config_cache_generation(namespace, scope_key),
    CONSTRAINT ck_system_config_cache_outbox_namespace
        CHECK (namespace ~ '^[a-z][a-z0-9]*(\.[a-z][a-z0-9]*)*$'),
    CONSTRAINT ck_system_config_cache_outbox_scope_key
        CHECK (scope_key ~ '^[a-zA-Z0-9][a-zA-Z0-9._:-]{0,127}$'),
    CONSTRAINT ck_system_config_cache_outbox_generation_value CHECK (generation >= 1),
    CONSTRAINT ck_system_config_cache_outbox_attempts CHECK (attempts >= 0),
    CONSTRAINT ck_system_config_cache_outbox_lock
        CHECK ((locked_until IS NULL AND lock_token IS NULL) OR
               (locked_until IS NOT NULL AND lock_token IS NOT NULL)),
    CONSTRAINT ck_system_config_cache_outbox_published_lock
        CHECK (published_at IS NULL OR (locked_until IS NULL AND lock_token IS NULL))
);

CREATE INDEX IF NOT EXISTS ix_system_config_cache_outbox_pending
    ON system_config_cache_outbox (available_at, id)
    WHERE published_at IS NULL;

-- 3. 第一阶段唯一 scope：system.setting/global，初始 generation 1 与初始 pending 事件。
-- 既有 row 不得被覆盖；值非法时迁移失败。
INSERT INTO system_config_cache_generation (
    namespace, scope_key, generation, created_at, updated_at
)
VALUES ('system.setting', 'global', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (namespace, scope_key) DO NOTHING;

DO $$
DECLARE
  current_generation BIGINT;
BEGIN
  SELECT generation INTO current_generation
  FROM system_config_cache_generation
  WHERE namespace = 'system.setting' AND scope_key = 'global'
  FOR UPDATE;
  IF current_generation IS NULL OR current_generation < 1 THEN
    RAISE EXCEPTION 'system.setting/global generation row is invalid';
  END IF;
END $$;

INSERT INTO system_config_cache_outbox (
    namespace, scope_key, generation, attempts, available_at, created_at, updated_at
)
VALUES ('system.setting', 'global', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (namespace, scope_key, generation) DO NOTHING;

-- 4. RBAC：page system:cacheGeneration:view 与 action system:cacheGeneration:list。
-- 只为存在活动 system directory 的平台插入；每个平台最多递增一次 menu_version。
CREATE TEMP TABLE tmp_cache_generation_platforms (platform_id BIGINT PRIMARY KEY) ON COMMIT DROP;

DO $$
DECLARE
  platform_row RECORD;
  locked_platform_id BIGINT;
  system_menu_id BIGINT;
  page_id BIGINT;
  changed BOOLEAN;
BEGIN
  FOR platform_row IN
    SELECT p.id FROM permission_auth_platform AS p
    WHERE p.deleted_at IS NULL AND p.is_enabled = 1
    ORDER BY p.id
  LOOP
    SELECT p.id INTO locked_platform_id
    FROM permission_auth_platform AS p
    WHERE p.id = platform_row.id
    FOR UPDATE;

    SELECT id INTO system_menu_id
    FROM permission_menu
    WHERE platform_id = platform_row.id
      AND code = 'system' AND menu_type = 'directory' AND deleted_at IS NULL
    FOR UPDATE;
    IF system_menu_id IS NULL THEN
      CONTINUE;
    END IF;

    IF (SELECT count(*) FROM permission_menu
        WHERE platform_id = platform_row.id AND code = 'system:cacheGeneration:view'
          AND deleted_at IS NULL) > 1 THEN
      RAISE EXCEPTION 'duplicate active system:cacheGeneration:view rows';
    END IF;
    IF (SELECT count(*) FROM permission_menu
        WHERE platform_id = platform_row.id AND code = 'system:cacheGeneration:list'
          AND deleted_at IS NULL) > 1 THEN
      RAISE EXCEPTION 'duplicate active system:cacheGeneration:list rows';
    END IF;

    IF EXISTS (SELECT 1 FROM permission_menu
      WHERE platform_id = platform_row.id AND deleted_at IS NULL
        AND path = '/system/cacheGeneration'
        AND (menu_type <> 'page' OR code <> 'system:cacheGeneration:view')) THEN
      RAISE EXCEPTION 'path /system/cacheGeneration is occupied by an incompatible node';
    END IF;
    IF EXISTS (SELECT 1 FROM permission_menu
      WHERE platform_id = platform_row.id AND deleted_at IS NULL
        AND component_path = 'system/cacheGeneration'
        AND (menu_type <> 'page' OR code <> 'system:cacheGeneration:view')) THEN
      RAISE EXCEPTION 'component path system/cacheGeneration is occupied by an incompatible node';
    END IF;

    changed := FALSE;
    SELECT id INTO page_id FROM permission_menu
    WHERE platform_id = platform_row.id AND code = 'system:cacheGeneration:view'
      AND deleted_at IS NULL;

    IF page_id IS NULL THEN
      INSERT INTO permission_menu
        (platform_id, parent_id, menu_type, name, code, i18n_key, path, component_path,
         icon, sort_order, is_enabled, is_hidden, created_at, updated_at)
      VALUES
        (platform_row.id, system_menu_id, 'page', '配置缓存代际', 'system:cacheGeneration:view',
         'navigation.systemCacheGeneration', '/system/cacheGeneration', 'system/cacheGeneration',
         'lucide:database-zap', 91, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
      RETURNING id INTO page_id;
      changed := TRUE;
    ELSE
      IF EXISTS (SELECT 1 FROM permission_menu WHERE id = page_id AND
        (parent_id IS DISTINCT FROM system_menu_id OR menu_type <> 'page' OR name <> '配置缓存代际' OR
         i18n_key IS DISTINCT FROM 'navigation.systemCacheGeneration' OR
         path IS DISTINCT FROM '/system/cacheGeneration' OR
         component_path IS DISTINCT FROM 'system/cacheGeneration' OR
         icon IS DISTINCT FROM 'lucide:database-zap' OR
         sort_order <> 91 OR is_enabled <> 1 OR is_hidden <> 0)) THEN
        RAISE EXCEPTION 'system:cacheGeneration:view menu shape mismatch';
      END IF;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM permission_menu
      WHERE platform_id = platform_row.id AND code = 'system:cacheGeneration:list'
        AND deleted_at IS NULL) THEN
      INSERT INTO permission_menu
        (platform_id, parent_id, menu_type, name, code, sort_order, is_enabled, is_hidden, created_at, updated_at)
      VALUES
        (platform_row.id, page_id, 'action', '查看配置缓存代际', 'system:cacheGeneration:list',
         0, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
      changed := TRUE;
    ELSE
      IF EXISTS (SELECT 1 FROM permission_menu
        WHERE platform_id = platform_row.id AND code = 'system:cacheGeneration:list' AND deleted_at IS NULL
          AND (parent_id IS DISTINCT FROM page_id OR menu_type <> 'action' OR name <> '查看配置缓存代际' OR
               i18n_key IS NOT NULL OR path IS NOT NULL OR component_path IS NOT NULL OR icon IS NOT NULL OR
               is_enabled <> 1 OR is_hidden <> 1)) THEN
        RAISE EXCEPTION 'system:cacheGeneration:list menu shape mismatch';
      END IF;
    END IF;

    IF changed THEN
      INSERT INTO tmp_cache_generation_platforms (platform_id) VALUES (platform_row.id)
      ON CONFLICT (platform_id) DO NOTHING;
    END IF;
  END LOOP;
END $$;

UPDATE permission_auth_platform AS p
SET menu_version = p.menu_version + 1, updated_at = CURRENT_TIMESTAMP
FROM tmp_cache_generation_platforms AS t
WHERE p.id = t.platform_id;

COMMIT;
