BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';

DO $$
DECLARE
  table_count INTEGER;
BEGIN
  SELECT count(*) INTO table_count
  FROM pg_class AS relation
  JOIN pg_namespace AS namespace ON namespace.oid = relation.relnamespace
  WHERE namespace.nspname = current_schema()
    AND relation.relkind = 'r'
    AND relation.relname IN ('system_scheduler_schedule','system_scheduler_job','system_scheduler_run');
  IF table_count NOT IN (0, 3) THEN
    RAISE EXCEPTION 'scheduler schema must be entirely absent or complete; found % of 3 tables', table_count;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS system_scheduler_schedule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  description VARCHAR(512) NOT NULL DEFAULT '',
  task_type VARCHAR(128) NOT NULL,
  cron_expression VARCHAR(128) NOT NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
  params JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_enabled SMALLINT NOT NULL DEFAULT 1,
  next_run_at TIMESTAMPTZ NULL,
  builtin_key VARCHAR(128) NULL,
  created_by BIGINT NULL,
  updated_by BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ NULL,
  CONSTRAINT fk_system_scheduler_schedule_created_by FOREIGN KEY (created_by) REFERENCES user_account(id) ON DELETE RESTRICT,
  CONSTRAINT fk_system_scheduler_schedule_updated_by FOREIGN KEY (updated_by) REFERENCES user_account(id) ON DELETE RESTRICT,
  CONSTRAINT ck_system_scheduler_schedule_name CHECK (btrim(name) <> ''),
  CONSTRAINT ck_system_scheduler_schedule_task_type CHECK (btrim(task_type) <> ''),
  CONSTRAINT ck_system_scheduler_schedule_cron CHECK (btrim(cron_expression) <> ''),
  CONSTRAINT ck_system_scheduler_schedule_timezone CHECK (btrim(timezone) <> ''),
  CONSTRAINT ck_system_scheduler_schedule_params CHECK (jsonb_typeof(params) = 'object'),
  CONSTRAINT ck_system_scheduler_schedule_enabled CHECK (is_enabled IN (0, 1)),
  CONSTRAINT ck_system_scheduler_schedule_builtin_key CHECK (builtin_key IS NULL OR btrim(builtin_key) <> '')
);

CREATE TABLE IF NOT EXISTS system_scheduler_job (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id BIGINT NULL,
  task_type VARCHAR(128) NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  trigger_source VARCHAR(16) NOT NULL,
  source_key VARCHAR(255) NULL,
  scheduled_at TIMESTAMPTZ NOT NULL,
  available_at TIMESTAMPTZ NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'scheduled',
  attempt_count INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL,
  queue VARCHAR(64) NOT NULL,
  timeout_seconds INTEGER NOT NULL,
  publish_token VARCHAR(64) NULL,
  publish_lease_until TIMESTAMPTZ NULL,
  run_token VARCHAR(64) NULL,
  run_lease_until TIMESTAMPTZ NULL,
  worker_id VARCHAR(128) NULL,
  retry_of_job_id BIGINT NULL,
  triggered_by BIGINT NULL,
  error_class VARCHAR(64) NOT NULL DEFAULT '',
  last_error VARCHAR(1024) NOT NULL DEFAULT '',
  completed_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_system_scheduler_job_schedule FOREIGN KEY (schedule_id) REFERENCES system_scheduler_schedule(id) ON DELETE SET NULL,
  CONSTRAINT fk_system_scheduler_job_retry_of FOREIGN KEY (retry_of_job_id) REFERENCES system_scheduler_job(id) ON DELETE SET NULL,
  CONSTRAINT fk_system_scheduler_job_triggered_by FOREIGN KEY (triggered_by) REFERENCES user_account(id) ON DELETE RESTRICT,
  CONSTRAINT ck_system_scheduler_job_task_type CHECK (btrim(task_type) <> ''),
  CONSTRAINT ck_system_scheduler_job_payload CHECK (jsonb_typeof(payload) = 'object'),
  CONSTRAINT ck_system_scheduler_job_trigger_source CHECK (trigger_source IN ('cron','manual','retry','business')),
  CONSTRAINT ck_system_scheduler_job_status CHECK (status IN ('scheduled','queued','running','completed','failed','canceled')),
  CONSTRAINT ck_system_scheduler_job_counters CHECK (attempt_count >= 0 AND max_attempts > 0 AND timeout_seconds > 0),
  CONSTRAINT ck_system_scheduler_job_publish_lease CHECK (
    (status = 'scheduled' AND ((publish_lease_until IS NULL AND publish_token IS NULL) OR (publish_lease_until IS NOT NULL AND publish_token IS NOT NULL)))
    OR (status = 'queued' AND publish_lease_until IS NOT NULL AND publish_token IS NOT NULL)
    OR (status NOT IN ('scheduled','queued') AND publish_lease_until IS NULL AND publish_token IS NULL)
  ),
  CONSTRAINT ck_system_scheduler_job_run_lease CHECK ((run_lease_until IS NULL AND run_token IS NULL) OR (run_lease_until IS NOT NULL AND run_token IS NOT NULL)),
  CONSTRAINT ck_system_scheduler_job_completed_at CHECK ((status IN ('completed','failed','canceled')) = (completed_at IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS system_scheduler_run (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT NOT NULL,
  attempt_no INTEGER NOT NULL,
  status VARCHAR(16) NOT NULL,
  worker_id VARCHAR(128) NOT NULL,
  started_at TIMESTAMPTZ NOT NULL,
  finished_at TIMESTAMPTZ NULL,
  duration_ms BIGINT NULL,
  error_class VARCHAR(64) NOT NULL DEFAULT '',
  error_message VARCHAR(1024) NOT NULL DEFAULT '',
  result_summary VARCHAR(1024) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_system_scheduler_run_job FOREIGN KEY (job_id) REFERENCES system_scheduler_job(id) ON DELETE CASCADE,
  CONSTRAINT ck_system_scheduler_run_attempt CHECK (attempt_no > 0),
  CONSTRAINT ck_system_scheduler_run_status CHECK (status IN ('running','succeeded','failed')),
  CONSTRAINT ck_system_scheduler_run_finished CHECK ((status = 'running' AND finished_at IS NULL) OR (status <> 'running' AND finished_at IS NOT NULL)),
  CONSTRAINT ck_system_scheduler_run_duration CHECK (duration_ms IS NULL OR duration_ms >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_system_scheduler_schedule_name_active
  ON system_scheduler_schedule (lower(name)) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_system_scheduler_schedule_builtin_active
  ON system_scheduler_schedule (builtin_key) WHERE deleted_at IS NULL AND builtin_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_system_scheduler_schedule_due
  ON system_scheduler_schedule (next_run_at, id) WHERE deleted_at IS NULL AND is_enabled = 1;
CREATE INDEX IF NOT EXISTS ix_system_scheduler_schedule_task_type
  ON system_scheduler_schedule (task_type, created_at DESC, id DESC) WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_system_scheduler_job_active_schedule
  ON system_scheduler_job (schedule_id) WHERE schedule_id IS NOT NULL AND status IN ('scheduled','queued','running');
CREATE UNIQUE INDEX IF NOT EXISTS ux_system_scheduler_job_source_key
  ON system_scheduler_job (task_type, source_key) WHERE source_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_system_scheduler_job_task_attempt
  ON system_scheduler_job (id, attempt_count);
CREATE INDEX IF NOT EXISTS ix_system_scheduler_job_publish
  ON system_scheduler_job (available_at, id) WHERE status = 'scheduled';
CREATE INDEX IF NOT EXISTS ix_system_scheduler_job_publish_lease
  ON system_scheduler_job (publish_lease_until, id) WHERE status = 'scheduled' AND publish_lease_until IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_system_scheduler_job_run_lease
  ON system_scheduler_job (run_lease_until, id) WHERE status = 'running' AND run_lease_until IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_system_scheduler_job_list
  ON system_scheduler_job (created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_system_scheduler_job_schedule_list
  ON system_scheduler_job (schedule_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_system_scheduler_job_terminal_cleanup
  ON system_scheduler_job (completed_at, id) WHERE status IN ('completed','failed','canceled');

CREATE UNIQUE INDEX IF NOT EXISTS ux_system_scheduler_run_job_attempt
  ON system_scheduler_run (job_id, attempt_no);
CREATE INDEX IF NOT EXISTS ix_system_scheduler_run_job_list
  ON system_scheduler_run (job_id, attempt_no DESC);
CREATE INDEX IF NOT EXISTS ix_system_scheduler_run_cleanup
  ON system_scheduler_run (finished_at, id) WHERE status IN ('succeeded','failed');

DO $$
DECLARE
  changed BOOLEAN := FALSE;
  next_generation BIGINT;
  existing_value TEXT;
BEGIN
  SELECT value INTO existing_value
  FROM system_setting
  WHERE setting_key = 'system.scheduler.history_retention_days' AND deleted_at IS NULL
  FOR UPDATE;

  IF existing_value IS NULL THEN
    INSERT INTO system_setting(setting_key,value,value_type,description,is_enabled,is_builtin,created_at,updated_at)
    VALUES('system.scheduler.history_retention_days','30',2,'调度器终态历史保留天数',1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
    changed := TRUE;
  ELSE
    IF existing_value !~ '^[0-9]+$' OR existing_value::BIGINT < 7 OR existing_value::BIGINT > 3650 THEN
      RAISE EXCEPTION 'invalid existing system.scheduler.history_retention_days';
    END IF;
    UPDATE system_setting
    SET value_type=2,description='调度器终态历史保留天数',is_enabled=1,is_builtin=1,updated_at=CURRENT_TIMESTAMP
    WHERE setting_key='system.scheduler.history_retention_days' AND deleted_at IS NULL
      AND (value_type<>2 OR description<>'调度器终态历史保留天数' OR is_enabled<>1 OR is_builtin<>1);
    changed := FOUND;
  END IF;

  IF changed THEN
    UPDATE system_config_cache_generation
    SET generation = generation + 1, updated_at = CURRENT_TIMESTAMP
    WHERE namespace='system.setting' AND scope_key='global'
    RETURNING generation INTO next_generation;
    IF next_generation IS NULL THEN
      RAISE EXCEPTION 'system.setting/global generation is missing';
    END IF;
    INSERT INTO system_config_cache_outbox(namespace,scope_key,generation,attempts,available_at,last_error,created_at,updated_at)
    VALUES('system.setting','global',next_generation,0,CURRENT_TIMESTAMP,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
    ON CONFLICT (namespace,scope_key,generation) DO NOTHING;
  END IF;
END $$;

DO $$
DECLARE
  platform_row RECORD;
  system_menu_id BIGINT;
  page_id BIGINT;
  action_row RECORD;
  menu_changed BOOLEAN;
  role_row RECORD;
  changed_rows INTEGER;
  affected_role_ids BIGINT[] := ARRAY[]::BIGINT[];
BEGIN
  FOR platform_row IN
    SELECT p.id AS platform_id
    FROM permission_auth_platform p
    JOIN permission_menu d ON d.platform_id=p.id AND d.code='system' AND d.menu_type='directory' AND d.deleted_at IS NULL
    WHERE p.code='admin' AND p.is_enabled=1 AND p.deleted_at IS NULL
    GROUP BY p.id
    ORDER BY p.id
  LOOP
    SELECT d.id INTO system_menu_id
    FROM permission_menu d
    WHERE d.platform_id=platform_row.platform_id AND d.code='system' AND d.menu_type='directory' AND d.deleted_at IS NULL
    FOR UPDATE;

    IF EXISTS (SELECT 1 FROM permission_menu WHERE platform_id=platform_row.platform_id AND deleted_at IS NULL AND path='/system/scheduler' AND code<>'system:scheduler:view') THEN
      RAISE EXCEPTION 'scheduler page path is occupied';
    END IF;
    SELECT id INTO page_id FROM permission_menu WHERE platform_id=platform_row.platform_id AND code='system:scheduler:view' AND deleted_at IS NULL;
    menu_changed := FALSE;
    IF page_id IS NULL THEN
      INSERT INTO permission_menu(platform_id,parent_id,menu_type,name,code,i18n_key,path,component_path,icon,sort_order,is_enabled,is_hidden,created_at,updated_at)
      VALUES(platform_row.platform_id,system_menu_id,'page','定时任务','system:scheduler:view','navigation.systemScheduler','/system/scheduler','system/scheduler','lucide:list-checks',92,1,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
      RETURNING id INTO page_id;
      menu_changed := TRUE;
    ELSE
      IF EXISTS (SELECT 1 FROM permission_menu WHERE id=page_id AND (parent_id IS DISTINCT FROM system_menu_id OR menu_type<>'page' OR name<>'定时任务' OR i18n_key IS DISTINCT FROM 'navigation.systemScheduler' OR path IS DISTINCT FROM '/system/scheduler' OR component_path IS DISTINCT FROM 'system/scheduler' OR icon IS DISTINCT FROM 'lucide:list-checks' OR sort_order<>92 OR is_enabled<>1 OR is_hidden<>0)) THEN
        RAISE EXCEPTION 'system:scheduler:view menu shape mismatch';
      END IF;
    END IF;

    FOR action_row IN SELECT * FROM (VALUES
      ('system:scheduler:list','查看执行记录',10),
      ('system:scheduler:detail','查看执行详情',20),
      ('system:scheduler:create','创建定时计划',30),
      ('system:scheduler:update','编辑定时计划',40),
      ('system:scheduler:status','启停定时计划',50),
      ('system:scheduler:delete','删除定时计划',60),
      ('system:scheduler:execute','立即执行任务',70),
      ('system:scheduler:retry','重试失败任务',80)
    ) AS actions(code,name,sort_order)
    LOOP
      IF EXISTS (SELECT 1 FROM permission_menu WHERE platform_id=platform_row.platform_id AND code=action_row.code AND deleted_at IS NULL AND (parent_id IS DISTINCT FROM page_id OR menu_type<>'action' OR name<>action_row.name OR i18n_key IS NOT NULL OR path IS NOT NULL OR component_path IS NOT NULL OR icon IS NOT NULL OR is_enabled<>1 OR is_hidden<>1)) THEN
        RAISE EXCEPTION 'scheduler action menu shape mismatch: %', action_row.code;
      END IF;
      IF NOT EXISTS (SELECT 1 FROM permission_menu WHERE platform_id=platform_row.platform_id AND code=action_row.code AND deleted_at IS NULL) THEN
        INSERT INTO permission_menu(platform_id,parent_id,menu_type,name,code,sort_order,is_enabled,is_hidden,created_at,updated_at)
        VALUES(platform_row.platform_id,page_id,'action',action_row.name,action_row.code,action_row.sort_order,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
        menu_changed := TRUE;
      END IF;
    END LOOP;

    FOR role_row IN SELECT id FROM permission_role WHERE is_enabled=1 AND deleted_at IS NULL ORDER BY id
    LOOP
      changed_rows := 0;
      INSERT INTO permission_role_menu(role_id,menu_id,created_at,updated_at)
      SELECT role_row.id,m.id,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP
      FROM permission_menu m
      WHERE m.platform_id=platform_row.platform_id
        AND m.deleted_at IS NULL
        AND m.code IN ('system:scheduler:view','system:scheduler:list','system:scheduler:detail','system:scheduler:create','system:scheduler:update','system:scheduler:status','system:scheduler:delete','system:scheduler:execute','system:scheduler:retry')
        AND NOT EXISTS (SELECT 1 FROM permission_role_menu rm WHERE rm.role_id=role_row.id AND rm.menu_id=m.id AND rm.deleted_at IS NULL);
      GET DIAGNOSTICS changed_rows=ROW_COUNT;
      IF changed_rows>0 THEN affected_role_ids:=array_append(affected_role_ids,role_row.id); END IF;
    END LOOP;

    IF menu_changed THEN
      UPDATE permission_auth_platform SET menu_version=menu_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=platform_row.platform_id;
    END IF;
  END LOOP;

  IF cardinality(affected_role_ids)>0 THEN
    UPDATE permission_access_version av SET version=av.version+1,updated_at=CURRENT_TIMESTAMP
    FROM user_account u
    WHERE u.id=av.user_id AND u.is_enabled=1 AND u.deleted_at IS NULL
      AND EXISTS (SELECT 1 FROM permission_user_role ur WHERE ur.user_id=av.user_id AND ur.role_id=ANY(affected_role_ids) AND ur.deleted_at IS NULL);
  END IF;
END $$;

INSERT INTO system_scheduler_schedule(name,description,task_type,cron_expression,timezone,params,is_enabled,next_run_at,builtin_key,created_at,updated_at)
VALUES
  ('实时事件历史清理','清理超过保留期的 durable realtime events','realtime.retention.cleanup','*/1 * * * *','Asia/Shanghai','{}'::jsonb,1,CURRENT_TIMESTAMP,'realtime.retention.cleanup',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  ('站内通知历史清理','清理超过保留期的站内通知历史','message.notification.retention.cleanup','*/1 * * * *','Asia/Shanghai','{}'::jsonb,1,CURRENT_TIMESTAMP,'message.notification.retention.cleanup',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  ('调度器历史清理','清理调度器终态 Job/Run 历史','system.scheduler.history.cleanup','30 3 * * *','Asia/Shanghai','{}'::jsonb,1,CURRENT_TIMESTAMP,'system.scheduler.history.cleanup',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT (lower(name)) WHERE deleted_at IS NULL DO NOTHING;

UPDATE system_scheduler_schedule
SET next_run_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP
WHERE deleted_at IS NULL AND is_enabled=1 AND next_run_at IS NULL
  AND builtin_key IN ('realtime.retention.cleanup','message.notification.retention.cleanup','system.scheduler.history.cleanup');

DROP TABLE IF EXISTS message_notification_dispatch_outbox;

COMMIT;
