BEGIN;

CREATE TABLE IF NOT EXISTS storage_upload_rule_code (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id BIGINT NOT NULL,
  platform_id BIGINT NOT NULL,
  code VARCHAR(64) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ NULL,
  CONSTRAINT fk_storage_upload_rule_code_rule FOREIGN KEY (rule_id) REFERENCES storage_upload_rule(id) ON DELETE CASCADE,
  CONSTRAINT fk_storage_upload_rule_code_platform FOREIGN KEY (platform_id) REFERENCES auth_platform(id) ON DELETE RESTRICT,
  CONSTRAINT ck_storage_upload_rule_code_value CHECK (length(btrim(code)) > 0)
);

INSERT INTO storage_upload_rule_code (rule_id, platform_id, code, deleted_at)
SELECT id, platform_id, code, deleted_at
FROM storage_upload_rule
WHERE code IS NOT NULL
ON CONFLICT DO NOTHING;

DROP INDEX IF EXISTS ux_storage_upload_rule_platform_code_active;

CREATE UNIQUE INDEX IF NOT EXISTS ux_storage_upload_rule_code_platform_code
  ON storage_upload_rule_code (platform_id, code)
  WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS ix_storage_upload_rule_code_rule
  ON storage_upload_rule_code (rule_id, id)
  WHERE deleted_at IS NULL;

ALTER TABLE storage_upload_rule
  DROP COLUMN IF EXISTS code;

COMMIT;
