<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useI18n } from 'vue-i18n'
import { useAccessStore } from '../../../store/access'
import { YesNo } from '../../../enums/yes-no'
import { listCosConfigs, createCosConfig, updateCosConfig, updateCosConfigStatus, testCosConfig, deleteCosConfig, type CosConfig } from '../../../api/storage/cosconfig'
import { listUploadRules, getUploadRulePageInit, createUploadRule, updateUploadRule, updateUploadRuleStatus, deleteUploadRule, type UploadRule, type PlatformOption, type ConfigSummary } from '../../../api/storage/uploadrule'

const { t } = useI18n(); const access = useAccessStore(); const activeTab=ref<'config'|'rules'>('config'); const loading=ref(false); const error=ref(''); const configs=ref<CosConfig[]>([]); const rules=ref<UploadRule[]>([]); const platforms=ref<PlatformOption[]>([]); const configOptions=ref<ConfigSummary[]>([]); const configDialog=ref(false); const ruleDialog=ref(false); const editingConfig=ref<number|null>(null); const editingRule=ref<number|null>(null)
interface ConfigForm { name:string; appId:string; secretId:string; secretKey:string; bucket:string; region:string; endpoint:string|null; bucketDomain:string|null; isEnabled:0|1; remark:string }
interface RuleForm { platformId:number; code:string; name:string; cosConfigId:number; pathPrefix:string; maxFileSizeBytes:number; maxFileCount:number; allowedExtensions:string[]; allowedMimeTypes:string[]; accessMode:'private'|'public'; isEnabled:0|1; remark:string }
const configForm=ref<ConfigForm>({name:'',appId:'',secretId:'',secretKey:'',bucket:'',region:'',endpoint:null,bucketDomain:null,isEnabled:YesNo.Yes,remark:''}); const ruleForm=ref<RuleForm>({platformId:0,code:'',name:'',cosConfigId:0,pathPrefix:'',maxFileSizeBytes:1048576,maxFileCount:1,allowedExtensions:[],allowedMimeTypes:[],accessMode:'private',isEnabled:YesNo.Yes,remark:''})
const can = (code:string)=>access.hasPermission(code); const canCreateConfig=computed(()=>can('storage:cos-config:create')); const canUpdateConfig=computed(()=>can('storage:cos-config:update')); const canCreateRule=computed(()=>can('storage:upload-rule:create')); const canUpdateRule=computed(()=>can('storage:upload-rule:update'))
async function loadConfigs(){loading.value=true;error.value='';try{const page=await listCosConfigs({page:1,pageSize:20});configs.value=page.list}catch(e){error.value=e instanceof Error?e.message:t('storage.loadFailed')}finally{loading.value=false}}
async function loadRules(){loading.value=true;error.value='';try{const page=await listUploadRules({page:1,pageSize:20});rules.value=page.list;const init=await getUploadRulePageInit();platforms.value=init.platforms;configOptions.value=init.configs}catch(e){error.value=e instanceof Error?e.message:t('storage.loadFailed')}finally{loading.value=false}}
async function switchTab(tab:string){activeTab.value=tab as 'config'|'rules';if(activeTab.value==='config')await loadConfigs();else await loadRules()}
function openConfig(row?:CosConfig){editingConfig.value=row?.id??null;configForm.value=row?{...row,secretId:'',secretKey:''}:{name:'',appId:'',secretId:'',secretKey:'',bucket:'',region:'',endpoint:null,bucketDomain:null,isEnabled:YesNo.Yes,remark:''};configDialog.value=true}
async function saveConfig(){if(!configForm.value.name||!configForm.value.appId||(!editingConfig.value&&( !configForm.value.secretId||!configForm.value.secretKey))){return}try{if(editingConfig.value)await updateCosConfig(editingConfig.value,configForm.value);else await createCosConfig(configForm.value);configDialog.value=false;await loadConfigs()}catch(e){ElMessage.error(e instanceof Error?e.message:t('storage.saveFailed'))}}
async function toggleConfig(row:CosConfig){try{await ElMessageBox.confirm(t('storage.confirmStatus'),'');await updateCosConfigStatus(row.id,row.isEnabled===YesNo.Yes?YesNo.No:YesNo.Yes);await loadConfigs()}catch{} }
async function testConfig(row:CosConfig){try{await testCosConfig(row.id);ElMessage.success(t('storage.testSuccess'))}catch(e){ElMessage.error(e instanceof Error?e.message:t('storage.testFailed'))}}
async function removeConfig(row:CosConfig){try{await ElMessageBox.confirm(t('storage.confirmDelete'),'');await deleteCosConfig(row.id);await loadConfigs()}catch{} }
function openRule(row?:UploadRule){editingRule.value=row?.id??null;ruleForm.value=row?{...row}:{platformId:platforms.value[0]?.id??0,code:'',name:'',cosConfigId:configOptions.value[0]?.id??0,pathPrefix:'',maxFileSizeBytes:1048576,maxFileCount:1,allowedExtensions:[],allowedMimeTypes:[],accessMode:'private',isEnabled:YesNo.Yes,remark:''};ruleDialog.value=true}
async function saveRule(){try{const payload={...ruleForm.value,allowedExtensions:Array.isArray(ruleForm.value.allowedExtensions)?ruleForm.value.allowedExtensions:String(ruleForm.value.allowedExtensions).split(',').map(v=>v.trim()).filter(Boolean),allowedMimeTypes:Array.isArray(ruleForm.value.allowedMimeTypes)?ruleForm.value.allowedMimeTypes:String(ruleForm.value.allowedMimeTypes).split(',').map(v=>v.trim()).filter(Boolean)};if(editingRule.value)await updateUploadRule(editingRule.value,payload);else await createUploadRule(payload);ruleDialog.value=false;await loadRules()}catch(e){ElMessage.error(e instanceof Error?e.message:t('storage.saveFailed'))}}
async function toggleRule(row:UploadRule){try{await updateUploadRuleStatus(row.id,row.isEnabled===YesNo.Yes?YesNo.No:YesNo.Yes);await loadRules()}catch(e){ElMessage.error(e instanceof Error?e.message:t('storage.saveFailed'))}}
async function removeRule(row:UploadRule){try{await ElMessageBox.confirm(t('storage.confirmDelete'),'');await deleteUploadRule(row.id);await loadRules()}catch{} }
onMounted(loadConfigs)
</script>

<template>
  <section class="storage-page">
    <header class="page-header"><div><p class="eyebrow">{{ t('navigation.cloud') }}</p><h1>{{ t('navigation.storageObject') }}</h1></div><el-button v-if="activeTab==='config'&&canCreateConfig" type="primary" @click="openConfig()">{{ t('storage.addConfig') }}</el-button><el-button v-if="activeTab==='rules'&&canCreateRule" type="primary" @click="openRule()">{{ t('storage.addRule') }}</el-button></header>
    <el-alert v-if="error" :title="error" type="error" show-icon />
    <el-tabs :model-value="activeTab" @tab-change="switchTab"><el-tab-pane name="config" :label="t('storage.configTab')"><el-table v-loading="loading" :data="configs"><el-table-column prop="name" :label="t('storage.name')"/><el-table-column prop="bucket" :label="t('storage.bucket')"/><el-table-column prop="region" :label="t('storage.region')"/><el-table-column :label="t('storage.credentials')"><template #default="{row}"><el-tag :type="row.hasCredentials?'success':'warning'">{{ row.hasCredentials?t('storage.configured'):t('storage.missing') }}</el-tag></template></el-table-column><el-table-column :label="t('storage.status')"><template #default="{row}"><el-tag>{{ row.isEnabled===1?t('storage.enabled'):t('storage.disabled') }}</el-tag></template></el-table-column><el-table-column :label="t('storage.actions')"><template #default="{row}"><el-button v-if="canUpdateConfig" link @click="openConfig(row)">{{t('storage.edit')}}</el-button><el-button v-if="can('storage:cos-config:test')" link @click="testConfig(row)">{{t('storage.test')}}</el-button><el-button v-if="can('storage:cos-config:status')" link @click="toggleConfig(row)">{{t('storage.toggle')}}</el-button><el-button v-if="can('storage:cos-config:delete')" link type="danger" @click="removeConfig(row)">{{t('storage.delete')}}</el-button></template></el-table-column></el-table></el-tab-pane><el-tab-pane name="rules" :label="t('storage.rulesTab')"><el-table v-loading="loading" :data="rules"><el-table-column prop="name" :label="t('storage.name')"/><el-table-column prop="platformName" :label="t('storage.platform')"/><el-table-column prop="cosConfigName" :label="t('storage.config')"/><el-table-column prop="pathPrefix" :label="t('storage.pathPrefix')"/><el-table-column :label="t('storage.status')"><template #default="{row}"><el-tag>{{row.isEnabled===1?t('storage.enabled'):t('storage.disabled')}}</el-tag></template></el-table-column><el-table-column :label="t('storage.actions')"><template #default="{row}"><el-button v-if="canUpdateRule" link @click="openRule(row)">{{t('storage.edit')}}</el-button><el-button v-if="can('storage:upload-rule:status')" link @click="toggleRule(row)">{{t('storage.toggle')}}</el-button><el-button v-if="can('storage:upload-rule:delete')" link type="danger" @click="removeRule(row)">{{t('storage.delete')}}</el-button></template></el-table-column></el-table></el-tab-pane></el-tabs>
    <el-dialog v-model="configDialog" :title="editingConfig?t('storage.editConfig'):t('storage.addConfig')"><el-form label-position="top"><el-form-item :label="t('storage.name')"><el-input v-model="configForm.name"/></el-form-item><el-form-item :label="t('storage.appId')"><el-input v-model="configForm.appId"/></el-form-item><el-form-item :label="t('storage.secretId')"><el-input v-model="configForm.secretId" type="password" show-password/></el-form-item><el-form-item :label="t('storage.secretKey')"><el-input v-model="configForm.secretKey" type="password" show-password/></el-form-item><el-form-item :label="t('storage.bucket')"><el-input v-model="configForm.bucket"/></el-form-item><el-form-item :label="t('storage.region')"><el-input v-model="configForm.region"/></el-form-item><el-form-item :label="t('storage.endpoint')"><el-input v-model="configForm.endpoint"/></el-form-item><el-form-item :label="t('storage.bucketDomain')"><el-input v-model="configForm.bucketDomain"/></el-form-item><el-form-item :label="t('storage.remark')"><el-input v-model="configForm.remark"/></el-form-item></el-form><template #footer><el-button @click="configDialog=false">{{t('storage.cancel')}}</el-button><el-button type="primary" @click="saveConfig">{{t('storage.save')}}</el-button></template></el-dialog>
    <el-dialog v-model="ruleDialog" :title="editingRule?t('storage.editRule'):t('storage.addRule')"><el-form label-position="top"><el-form-item v-if="!editingRule" :label="t('storage.platform')"><el-select v-model="ruleForm.platformId"><el-option v-for="p in platforms" :key="p.id" :label="p.name" :value="p.id"/></el-select></el-form-item><el-form-item v-if="!editingRule" :label="t('storage.code')"><el-input v-model="ruleForm.code"/></el-form-item><el-form-item :label="t('storage.name')"><el-input v-model="ruleForm.name"/></el-form-item><el-form-item :label="t('storage.config')"><el-select v-model="ruleForm.cosConfigId"><el-option v-for="c in configOptions" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item><el-form-item :label="t('storage.pathPrefix')"><el-input v-model="ruleForm.pathPrefix"/></el-form-item><el-form-item :label="t('storage.extensions')"><el-input v-model="ruleForm.allowedExtensions" placeholder="png,jpg"/></el-form-item><el-form-item :label="t('storage.mimeTypes')"><el-input v-model="ruleForm.allowedMimeTypes" placeholder="image/png"/></el-form-item><el-form-item :label="t('storage.accessMode')"><el-radio-group v-model="ruleForm.accessMode"><el-radio label="private">{{t('storage.private')}}</el-radio><el-radio label="public">{{t('storage.public')}}</el-radio></el-radio-group></el-form-item></el-form><template #footer><el-button @click="ruleDialog=false">{{t('storage.cancel')}}</el-button><el-button type="primary" @click="saveRule">{{t('storage.save')}}</el-button></template></el-dialog>
  </section>
</template>

<style scoped>
.storage-page{padding:24px;max-width:1440px;margin:auto}.page-header{display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:20px}.eyebrow{margin:0 0 4px;color:var(--el-text-color-secondary);font-size:12px;text-transform:uppercase;letter-spacing:.08em}.page-header h1{margin:0;font-size:26px;font-weight:650}.el-tabs{background:var(--el-bg-color);border:1px solid var(--el-border-color-light);padding:0 18px 18px}.el-table{margin-top:8px}
</style>
