package recipientrule

import (
	"context"
	"errors"
	"os"
	"testing"

	projectconfig "admin/server/internal/config"
	"admin/server/internal/database/testschema"
	"admin/server/internal/shared/cacheGeneration"
	"admin/server/internal/shared/yesno"
	"github.com/joho/godotenv"
	"gorm.io/gorm"
)

type runtimeCoordinatorFunc func(context.Context, func(context.Context, int64) (cachegeneration.MutationResult, error)) error

func (f runtimeCoordinatorFunc) Mutate(ctx context.Context, change func(context.Context, int64) (cachegeneration.MutationResult, error)) error {
	return f(ctx, change)
}

func TestServiceAppliesGlobalExactRuleBeforeDomainAndSupportsCRUD(t *testing.T) {
	database, ctx := openServiceDatabase(t)
	service := NewService(configuredRepository(database))
	generation := int64(1)
	service.SetRuntimeCoordinator(runtimeCoordinatorFunc(func(ctx context.Context, change func(context.Context, int64) (cachegeneration.MutationResult, error)) error {
		result, err := change(ctx, generation)
		if err == nil && result.Changed {
			generation = result.Generation
		}
		return err
	}))
	domainID, err := service.Create(ctx, Input{
		Scope: ScopeDomain, Pattern: "example.com", Action: ActionDeny,
		Name: "deny example", IsEnabled: yesno.Yes,
	})
	if err != nil {
		t.Fatal(err)
	}
	exactID, err := service.Create(ctx, Input{
		Scope: ScopeEmail, Pattern: "user@example.com", Action: ActionAllow,
		Name: "allow user", IsEnabled: yesno.Yes,
	})
	if err != nil {
		t.Fatal(err)
	}
	decision, err := service.Evaluate(ctx, "user@example.com", SendModeBusiness)
	if err != nil || !decision.Allowed || decision.RuleID != exactID {
		t.Fatalf("exact decision=%+v err=%v", decision, err)
	}
	decision, err = service.Evaluate(ctx, "other@example.com", SendModeAdminTest)
	if err != nil || decision.Allowed || decision.RuleID != domainID {
		t.Fatalf("domain decision=%+v err=%v", decision, err)
	}
	if err := service.SetStatus(ctx, exactID, yesno.No); err != nil {
		t.Fatal(err)
	}
	decision, err = service.Evaluate(ctx, "user@example.com", SendModeBusiness)
	if err != nil || decision.Allowed || decision.RuleID != domainID {
		t.Fatalf("disabled exact decision=%+v err=%v", decision, err)
	}
	if err := service.Delete(ctx, domainID); err != nil {
		t.Fatal(err)
	}
	decision, err = service.Evaluate(ctx, "other@example.com", SendModeBusiness)
	if err != nil || !decision.Allowed || decision.Reason != "default_allow" {
		t.Fatalf("default decision=%+v err=%v", decision, err)
	}
}

func TestNormalizeAndDomainBoundary(t *testing.T) {
	value, err := NormalizeRecipient(" User@Example.COM ")
	if err != nil || value != "user@example.com" {
		t.Fatalf("%q %v", value, err)
	}
	if !matchesDomain(value, "example.com") || !matchesDomain("a.b@example.com", "example.com") || matchesDomain("user@badexample.com", "example.com") || matchesDomain("user@example.com.evil", "example.com") {
		t.Fatal("domain boundary mismatch")
	}
	if _, err = NormalizeRule(ScopeDomain, "-example.com"); err == nil {
		t.Fatal("invalid domain accepted")
	}
}

func TestServiceDoesNotCreateWhenRuntimeInvalidationFails(t *testing.T) {
	database, ctx := openServiceDatabase(t)
	service := NewService(configuredRepository(database))
	service.SetRuntimeCoordinator(runtimeCoordinatorFunc(func(context.Context, func(context.Context, int64) (cachegeneration.MutationResult, error)) error {
		return errors.New("redis unavailable")
	}))
	if _, err := service.Create(ctx, Input{
		Scope: ScopeDomain, Pattern: "example.com", Action: ActionDeny,
		Name: "deny example", IsEnabled: yesno.Yes,
	}); err == nil {
		t.Fatal("create succeeded while runtime invalidation failed")
	}
	var count int64
	if err := database.WithContext(ctx).Model(&Model{}).Count(&count).Error; err != nil || count != 0 {
		t.Fatalf("recipient rule rows=%d err=%v", count, err)
	}
}

func openServiceDatabase(t *testing.T) (*gorm.DB, context.Context) {
	t.Helper()
	if testing.Short() {
		t.Skip("PostgreSQL integration")
	}
	_ = godotenv.Load("../../../../../.env")
	settings, err := projectconfig.LoadWorker(os.LookupEnv)
	if err != nil {
		t.Fatal(err)
	}
	database, ctx := testschema.Open(t, settings.PostgresDSN, "test_mail_recipient_rule")
	if err := database.WithContext(ctx).Exec(`
CREATE TABLE message_mail_recipient_rule(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,scope varchar(16) NOT NULL,
 pattern varchar(254) NOT NULL,action varchar(16) NOT NULL,name varchar(128) NOT NULL,
 remark varchar(512) NOT NULL,is_enabled smallint NOT NULL,created_at timestamptz NOT NULL,
 updated_at timestamptz NOT NULL,deleted_at timestamptz);
CREATE UNIQUE INDEX ux_message_mail_rule_scope_pattern_action_active
 ON message_mail_recipient_rule(scope,pattern,action) WHERE deleted_at IS NULL;
CREATE TABLE system_config_cache_generation(namespace varchar(128) NOT NULL,scope_key varchar(128) NOT NULL,generation bigint NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(namespace,scope_key));
CREATE TABLE system_config_cache_outbox(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,namespace varchar(128) NOT NULL,scope_key varchar(128) NOT NULL,generation bigint NOT NULL,attempts integer NOT NULL DEFAULT 0,available_at timestamptz NOT NULL DEFAULT now(),locked_until timestamptz,lock_token varchar(64),last_error varchar(512) NOT NULL DEFAULT '',published_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(namespace,scope_key,generation),FOREIGN KEY(namespace,scope_key) REFERENCES system_config_cache_generation(namespace,scope_key));
INSERT INTO system_config_cache_generation(namespace,scope_key,generation) VALUES ('message.mail','global',1);`).Error; err != nil {
		t.Fatal(err)
	}
	return database, ctx
}

func configuredRepository(database *gorm.DB) *Repository {
	repository := NewRepository(database)
	repository.SetGenerations(cachegeneration.NewRepository(database), cachegeneration.Scope{Namespace: "message.mail", ScopeKey: "global"})
	return repository
}
