package mail

import (
	"context"
	"errors"
	"os"
	"sync"
	"testing"
	"time"

	"admin/server/internal/config"
	"admin/server/internal/database/testschema"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/joho/godotenv"
	"gorm.io/gorm"
)

func TestIsUniqueViolationRecognizesPostgresConstraint(t *testing.T) {
	err := &pgconn.PgError{Code: "23505"}
	if !isUniqueViolation(err) {
		t.Fatal("expected PostgreSQL unique violation to be recognized")
	}
	if isUniqueViolation(errors.New("duplicate")) {
		t.Fatal("plain errors must not be treated as unique violations")
	}
}

func TestFindActiveChallengeReturnsPendingAndSentLogs(t *testing.T) {
	db, ctx := openMailRepositoryDatabase(t)
	repository := NewRepository(db)
	now := time.Now().UTC()
	challenge := "challenge-1"
	type createResult struct {
		row Log
		err error
	}
	var wg sync.WaitGroup
	results := make(chan createResult, 2)
	for i := 0; i < 2; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			row, err := repository.CreatePendingLog(ctx, &Log{PlatformID: 1, ChallengeID: &challenge, Scene: SceneLogin, TemplateID: 47941, ToEmail: "user@example.com", Subject: "subject", Status: StatusPending, CreatedAt: now, UpdatedAt: now})
			results <- createResult{row: row, err: err}
		}()
	}
	wg.Wait()
	close(results)
	var first Log
	var uniqueErrors int
	for result := range results {
		if result.err == nil {
			first = result.row
		} else if isUniqueViolation(result.err) {
			uniqueErrors++
		} else {
			t.Fatalf("concurrent create error = %v", result.err)
		}
	}
	if first.ID == 0 || uniqueErrors != 1 {
		t.Fatalf("concurrent creates = row=%+v uniqueErrors=%d", first, uniqueErrors)
	}
	found, err := repository.FindActiveChallenge(ctx, 1, challenge)
	if err != nil || found.ID != first.ID || found.Status != StatusPending {
		t.Fatalf("pending active log = %+v,%v", found, err)
	}
	if err := db.WithContext(ctx).Model(&Log{}).Where("id = ?", first.ID).Update("status", StatusSent).Error; err != nil {
		t.Fatal(err)
	}
	found, err = repository.FindActiveChallenge(ctx, 1, challenge)
	if err != nil || found.ID != first.ID || found.Status != StatusSent {
		t.Fatalf("sent active log = %+v,%v", found, err)
	}
}

func openMailRepositoryDatabase(t *testing.T) (*gorm.DB, context.Context) {
	t.Helper()
	if testing.Short() {
		t.Skip("PostgreSQL integration test")
	}
	_ = godotenv.Load("../../../../.env")
	settings, err := config.LoadWorker(os.LookupEnv)
	if err != nil {
		t.Fatal(err)
	}
	db, ctx := testschema.Open(t, settings.PostgresDSN, "test_mail_repository")
	if err := db.WithContext(ctx).Exec(`
		CREATE TABLE system_mail_log (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			platform_id BIGINT NOT NULL,
			challenge_id VARCHAR(128),
			user_id BIGINT,
			scene VARCHAR(32) NOT NULL,
			template_id INTEGER NOT NULL,
			to_email VARCHAR(254) NOT NULL,
			subject VARCHAR(255) NOT NULL,
			status VARCHAR(16) NOT NULL,
			request_id VARCHAR(128) NOT NULL DEFAULT '',
			message_id VARCHAR(128) NOT NULL DEFAULT '',
			error_code VARCHAR(128) NOT NULL DEFAULT '',
			error_summary VARCHAR(512) NOT NULL DEFAULT '',
			latency_ms BIGINT NOT NULL DEFAULT 0,
			sent_at TIMESTAMPTZ,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			deleted_at TIMESTAMPTZ
		);
		CREATE UNIQUE INDEX ux_system_mail_log_platform_challenge_active ON system_mail_log(platform_id, challenge_id) WHERE deleted_at IS NULL AND challenge_id IS NOT NULL;
	`).Error; err != nil {
		t.Fatal(err)
	}
	return db, ctx
}
