package mail

import (
	"context"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"admin/server/internal/shared/yesno"
)

type countingSender struct {
	calls atomic.Int32
}

func (s *countingSender) Send(context.Context, SendInput) (ProviderSendResult, error) {
	s.calls.Add(1)
	return ProviderSendResult{RequestID: "request-1", MessageID: "message-1"}, nil
}

func TestSendConcurrentChallengeUsesDatabaseUniqueness(t *testing.T) {
	db, ctx := openMailRepositoryDatabase(t)
	if err := db.WithContext(ctx).Exec(`
		CREATE TABLE system_mail_config (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			platform_id BIGINT NOT NULL,
			secret_id_ciphertext TEXT NOT NULL DEFAULT '',
			secret_key_ciphertext TEXT NOT NULL DEFAULT '',
			secret_id_hint VARCHAR(32) NOT NULL DEFAULT '',
			secret_key_hint VARCHAR(32) NOT NULL DEFAULT '',
			region VARCHAR(64) NOT NULL,
			endpoint VARCHAR(255),
			from_email VARCHAR(254) NOT NULL,
			from_name VARCHAR(128) NOT NULL,
			reply_to VARCHAR(254),
			ttl_minutes SMALLINT NOT NULL,
			is_enabled SMALLINT NOT NULL,
			last_test_at TIMESTAMPTZ,
			last_test_error VARCHAR(512) NOT NULL DEFAULT '',
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			deleted_at TIMESTAMPTZ
		);
		CREATE TABLE system_mail_template (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			platform_id BIGINT NOT NULL,
			scene VARCHAR(32) NOT NULL,
			name VARCHAR(128) NOT NULL,
			subject VARCHAR(255) NOT NULL,
			tencent_template_id INTEGER NOT NULL,
			variables JSONB NOT NULL,
			example_variables JSONB NOT NULL,
			is_enabled SMALLINT NOT NULL,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			deleted_at TIMESTAMPTZ
		);
	`).Error; err != nil {
		t.Fatal(err)
	}
	now := time.Now().UTC()
	if err := db.WithContext(ctx).Exec(`INSERT INTO system_mail_config (platform_id, region, from_email, from_name, ttl_minutes, is_enabled, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`, 1, "ap-guangzhou", "sender@example.com", "Sender", 10, yesno.Yes, now, now).Error; err != nil {
		t.Fatal(err)
	}
	if err := db.WithContext(ctx).Exec(`INSERT INTO system_mail_template (platform_id, scene, name, subject, tencent_template_id, variables, example_variables, is_enabled, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?::jsonb, ?::jsonb, ?, ?, ?)`, 1, SceneLogin, "Login", "Login code", 47941, `{"code":"123456","ttl_minutes":"10"}`, `{"code":"123456","ttl_minutes":"10"}`, yesno.Yes, now, now).Error; err != nil {
		t.Fatal(err)
	}

	sender := &countingSender{}
	service := NewService(NewRepository(db), nil, sender, nil, nil)
	in := BusinessSendInput{PlatformID: 1, ChallengeID: "challenge-1", Scene: SceneLogin, ToEmail: "user@example.com", Variables: map[string]string{"code": "123456", "ttl_minutes": "10"}}
	start := make(chan struct{})
	results := make(chan struct {
		result SendResult
		err    error
	}, 2)
	var wg sync.WaitGroup
	for i := 0; i < 2; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			<-start
			result, err := service.send(ctx, in, SendModeAdminTest)
			results <- struct {
				result SendResult
				err    error
			}{result: result, err: err}
		}()
	}
	close(start)
	wg.Wait()
	close(results)
	var logID int64
	for result := range results {
		if result.err != nil {
			t.Fatalf("concurrent send error = %v", result.err)
		}
		if result.result.LogID == 0 || (result.result.Status != StatusPending && result.result.Status != StatusSent) {
			t.Fatalf("concurrent send result = %+v", result.result)
		}
		if logID == 0 {
			logID = result.result.LogID
		} else if result.result.LogID != logID {
			t.Fatalf("concurrent sends used different logs: %d and %d", logID, result.result.LogID)
		}
	}
	if sender.calls.Load() != 1 {
		t.Fatalf("sender calls = %d, want 1", sender.calls.Load())
	}
	var count int64
	if err := db.WithContext(ctx).Model(&Log{}).Where("platform_id = ? AND challenge_id = ? AND deleted_at IS NULL", 1, in.ChallengeID).Count(&count).Error; err != nil {
		t.Fatal(err)
	}
	if count != 1 {
		t.Fatalf("active challenge logs = %d, want 1", count)
	}
}
